// Code generated by protoc-gen-go.
// source: st.proto
// DO NOT EDIT!

/*
Package stonesthrow is a generated protocol buffer package.

It is generated from these files:
	st.proto

It has these top-level messages:
	ShellCommand
	RepositoryState
	RunState
	BuilderJob
	BuilderJobs
	GitRepositoryInfo
	LogEvent
	BeginCommandEvent
	CommandOutputEvent
	EndCommandEvent
	GitBranchTaskEvent
	ZippedContentEvent
	JobEvent
	BuildOptions
	TargetList
	BranchList
	RunOptions
	ClobberOptions
	PingOptions
	PingResult
	FetchFileOptions
	BranchConfigOptions
*/
package stonesthrow

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/duration"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LogEvent_Severity int32

const (
	LogEvent_ERROR LogEvent_Severity = 0
	LogEvent_INFO  LogEvent_Severity = 1
	LogEvent_DEBUG LogEvent_Severity = 2
)

var LogEvent_Severity_name = map[int32]string{
	0: "ERROR",
	1: "INFO",
	2: "DEBUG",
}
var LogEvent_Severity_value = map[string]int32{
	"ERROR": 0,
	"INFO":  1,
	"DEBUG": 2,
}

func (x LogEvent_Severity) String() string {
	return proto.EnumName(LogEvent_Severity_name, int32(x))
}
func (LogEvent_Severity) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

type CommandOutputEvent_Stream int32

const (
	CommandOutputEvent_OUT CommandOutputEvent_Stream = 0
	CommandOutputEvent_ERR CommandOutputEvent_Stream = 1
)

var CommandOutputEvent_Stream_name = map[int32]string{
	0: "OUT",
	1: "ERR",
}
var CommandOutputEvent_Stream_value = map[string]int32{
	"OUT": 0,
	"ERR": 1,
}

func (x CommandOutputEvent_Stream) String() string {
	return proto.EnumName(CommandOutputEvent_Stream_name, int32(x))
}
func (CommandOutputEvent_Stream) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 0} }

type GitBranchTaskEvent_Result int32

const (
	GitBranchTaskEvent_SUCCEEDED GitBranchTaskEvent_Result = 0
	GitBranchTaskEvent_FAILED    GitBranchTaskEvent_Result = 1
)

var GitBranchTaskEvent_Result_name = map[int32]string{
	0: "SUCCEEDED",
	1: "FAILED",
}
var GitBranchTaskEvent_Result_value = map[string]int32{
	"SUCCEEDED": 0,
	"FAILED":    1,
}

func (x GitBranchTaskEvent_Result) String() string {
	return proto.EnumName(GitBranchTaskEvent_Result_name, int32(x))
}
func (GitBranchTaskEvent_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{10, 0}
}

type ClobberOptions_Target int32

const (
	ClobberOptions_SOURCE ClobberOptions_Target = 0
	ClobberOptions_OUTPUT ClobberOptions_Target = 1
)

var ClobberOptions_Target_name = map[int32]string{
	0: "SOURCE",
	1: "OUTPUT",
}
var ClobberOptions_Target_value = map[string]int32{
	"SOURCE": 0,
	"OUTPUT": 1,
}

func (x ClobberOptions_Target) String() string {
	return proto.EnumName(ClobberOptions_Target_name, int32(x))
}
func (ClobberOptions_Target) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{17, 0} }

type ShellCommand struct {
	Command   []string `protobuf:"bytes,1,rep,name=command" json:"command,omitempty"`
	Directory string   `protobuf:"bytes,2,opt,name=directory" json:"directory,omitempty"`
	Host      string   `protobuf:"bytes,3,opt,name=host" json:"host,omitempty"`
}

func (m *ShellCommand) Reset()                    { *m = ShellCommand{} }
func (m *ShellCommand) String() string            { return proto.CompactTextString(m) }
func (*ShellCommand) ProtoMessage()               {}
func (*ShellCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ShellCommand) GetCommand() []string {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *ShellCommand) GetDirectory() string {
	if m != nil {
		return m.Directory
	}
	return ""
}

func (m *ShellCommand) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

type RepositoryState struct {
	Repository string `protobuf:"bytes,2,opt,name=repository" json:"repository,omitempty"`
	Revision   string `protobuf:"bytes,3,opt,name=revision" json:"revision,omitempty"`
}

func (m *RepositoryState) Reset()                    { *m = RepositoryState{} }
func (m *RepositoryState) String() string            { return proto.CompactTextString(m) }
func (*RepositoryState) ProtoMessage()               {}
func (*RepositoryState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RepositoryState) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *RepositoryState) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

type RunState struct {
	StartTime *google_protobuf1.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	Running   bool                        `protobuf:"varint,2,opt,name=running" json:"running,omitempty"`
	EndTime   *google_protobuf1.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
}

func (m *RunState) Reset()                    { *m = RunState{} }
func (m *RunState) String() string            { return proto.CompactTextString(m) }
func (*RunState) ProtoMessage()               {}
func (*RunState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RunState) GetStartTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *RunState) GetRunning() bool {
	if m != nil {
		return m.Running
	}
	return false
}

func (m *RunState) GetEndTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

type BuilderJob struct {
	Command    *ShellCommand             `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
	State      *RunState                 `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	SystemTime *google_protobuf.Duration `protobuf:"bytes,3,opt,name=system_time,json=systemTime" json:"system_time,omitempty"`
	UserTime   *google_protobuf.Duration `protobuf:"bytes,4,opt,name=user_time,json=userTime" json:"user_time,omitempty"`
}

func (m *BuilderJob) Reset()                    { *m = BuilderJob{} }
func (m *BuilderJob) String() string            { return proto.CompactTextString(m) }
func (*BuilderJob) ProtoMessage()               {}
func (*BuilderJob) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BuilderJob) GetCommand() *ShellCommand {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *BuilderJob) GetState() *RunState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *BuilderJob) GetSystemTime() *google_protobuf.Duration {
	if m != nil {
		return m.SystemTime
	}
	return nil
}

func (m *BuilderJob) GetUserTime() *google_protobuf.Duration {
	if m != nil {
		return m.UserTime
	}
	return nil
}

type BuilderJobs struct {
	Jobs []*BuilderJob `protobuf:"bytes,1,rep,name=jobs" json:"jobs,omitempty"`
}

func (m *BuilderJobs) Reset()                    { *m = BuilderJobs{} }
func (m *BuilderJobs) String() string            { return proto.CompactTextString(m) }
func (*BuilderJobs) ProtoMessage()               {}
func (*BuilderJobs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BuilderJobs) GetJobs() []*BuilderJob {
	if m != nil {
		return m.Jobs
	}
	return nil
}

type GitRepositoryInfo struct {
	Branches  []*GitRepositoryInfo_Branch   `protobuf:"bytes,1,rep,name=branches" json:"branches,omitempty"`
	Upstreams []*GitRepositoryInfo_Upstream `protobuf:"bytes,2,rep,name=upstreams" json:"upstreams,omitempty"`
}

func (m *GitRepositoryInfo) Reset()                    { *m = GitRepositoryInfo{} }
func (m *GitRepositoryInfo) String() string            { return proto.CompactTextString(m) }
func (*GitRepositoryInfo) ProtoMessage()               {}
func (*GitRepositoryInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GitRepositoryInfo) GetBranches() []*GitRepositoryInfo_Branch {
	if m != nil {
		return m.Branches
	}
	return nil
}

func (m *GitRepositoryInfo) GetUpstreams() []*GitRepositoryInfo_Upstream {
	if m != nil {
		return m.Upstreams
	}
	return nil
}

type GitRepositoryInfo_Branch struct {
	Name            string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Revision        string            `protobuf:"bytes,2,opt,name=revision" json:"revision,omitempty"`
	RevisionsAhead  int32             `protobuf:"varint,3,opt,name=revisions_ahead,json=revisionsAhead" json:"revisions_ahead,omitempty"`
	RevisionsBehind int32             `protobuf:"varint,4,opt,name=revisions_behind,json=revisionsBehind" json:"revisions_behind,omitempty"`
	Config          map[string]string `protobuf:"bytes,5,rep,name=config" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *GitRepositoryInfo_Branch) Reset()                    { *m = GitRepositoryInfo_Branch{} }
func (m *GitRepositoryInfo_Branch) String() string            { return proto.CompactTextString(m) }
func (*GitRepositoryInfo_Branch) ProtoMessage()               {}
func (*GitRepositoryInfo_Branch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

func (m *GitRepositoryInfo_Branch) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GitRepositoryInfo_Branch) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

func (m *GitRepositoryInfo_Branch) GetRevisionsAhead() int32 {
	if m != nil {
		return m.RevisionsAhead
	}
	return 0
}

func (m *GitRepositoryInfo_Branch) GetRevisionsBehind() int32 {
	if m != nil {
		return m.RevisionsBehind
	}
	return 0
}

func (m *GitRepositoryInfo_Branch) GetConfig() map[string]string {
	if m != nil {
		return m.Config
	}
	return nil
}

type GitRepositoryInfo_Upstream struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	PushUrl  string `protobuf:"bytes,2,opt,name=push_url,json=pushUrl" json:"push_url,omitempty"`
	FetchUrl string `protobuf:"bytes,3,opt,name=fetch_url,json=fetchUrl" json:"fetch_url,omitempty"`
}

func (m *GitRepositoryInfo_Upstream) Reset()                    { *m = GitRepositoryInfo_Upstream{} }
func (m *GitRepositoryInfo_Upstream) String() string            { return proto.CompactTextString(m) }
func (*GitRepositoryInfo_Upstream) ProtoMessage()               {}
func (*GitRepositoryInfo_Upstream) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 1} }

func (m *GitRepositoryInfo_Upstream) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GitRepositoryInfo_Upstream) GetPushUrl() string {
	if m != nil {
		return m.PushUrl
	}
	return ""
}

func (m *GitRepositoryInfo_Upstream) GetFetchUrl() string {
	if m != nil {
		return m.FetchUrl
	}
	return ""
}

type LogEvent struct {
	Host     string            `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	Msg      string            `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Severity LogEvent_Severity `protobuf:"varint,3,opt,name=severity,enum=stonesthrow.LogEvent_Severity" json:"severity,omitempty"`
}

func (m *LogEvent) Reset()                    { *m = LogEvent{} }
func (m *LogEvent) String() string            { return proto.CompactTextString(m) }
func (*LogEvent) ProtoMessage()               {}
func (*LogEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *LogEvent) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *LogEvent) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LogEvent) GetSeverity() LogEvent_Severity {
	if m != nil {
		return m.Severity
	}
	return LogEvent_ERROR
}

type BeginCommandEvent struct {
	Command *ShellCommand `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
}

func (m *BeginCommandEvent) Reset()                    { *m = BeginCommandEvent{} }
func (m *BeginCommandEvent) String() string            { return proto.CompactTextString(m) }
func (*BeginCommandEvent) ProtoMessage()               {}
func (*BeginCommandEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *BeginCommandEvent) GetCommand() *ShellCommand {
	if m != nil {
		return m.Command
	}
	return nil
}

type CommandOutputEvent struct {
	Stream CommandOutputEvent_Stream `protobuf:"varint,1,opt,name=stream,enum=stonesthrow.CommandOutputEvent_Stream" json:"stream,omitempty"`
	Output string                    `protobuf:"bytes,2,opt,name=output" json:"output,omitempty"`
}

func (m *CommandOutputEvent) Reset()                    { *m = CommandOutputEvent{} }
func (m *CommandOutputEvent) String() string            { return proto.CompactTextString(m) }
func (*CommandOutputEvent) ProtoMessage()               {}
func (*CommandOutputEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CommandOutputEvent) GetStream() CommandOutputEvent_Stream {
	if m != nil {
		return m.Stream
	}
	return CommandOutputEvent_OUT
}

func (m *CommandOutputEvent) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

type EndCommandEvent struct {
	ReturnCode int32                     `protobuf:"varint,1,opt,name=return_code,json=returnCode" json:"return_code,omitempty"`
	SystemTime *google_protobuf.Duration `protobuf:"bytes,2,opt,name=system_time,json=systemTime" json:"system_time,omitempty"`
	UserTime   *google_protobuf.Duration `protobuf:"bytes,3,opt,name=user_time,json=userTime" json:"user_time,omitempty"`
}

func (m *EndCommandEvent) Reset()                    { *m = EndCommandEvent{} }
func (m *EndCommandEvent) String() string            { return proto.CompactTextString(m) }
func (*EndCommandEvent) ProtoMessage()               {}
func (*EndCommandEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *EndCommandEvent) GetReturnCode() int32 {
	if m != nil {
		return m.ReturnCode
	}
	return 0
}

func (m *EndCommandEvent) GetSystemTime() *google_protobuf.Duration {
	if m != nil {
		return m.SystemTime
	}
	return nil
}

func (m *EndCommandEvent) GetUserTime() *google_protobuf.Duration {
	if m != nil {
		return m.UserTime
	}
	return nil
}

type GitBranchTaskEvent struct {
	Branch   string                    `protobuf:"bytes,1,opt,name=branch" json:"branch,omitempty"`
	Result   GitBranchTaskEvent_Result `protobuf:"varint,2,opt,name=result,enum=stonesthrow.GitBranchTaskEvent_Result" json:"result,omitempty"`
	Revision string                    `protobuf:"bytes,3,opt,name=revision" json:"revision,omitempty"`
	Reason   string                    `protobuf:"bytes,4,opt,name=reason" json:"reason,omitempty"`
}

func (m *GitBranchTaskEvent) Reset()                    { *m = GitBranchTaskEvent{} }
func (m *GitBranchTaskEvent) String() string            { return proto.CompactTextString(m) }
func (*GitBranchTaskEvent) ProtoMessage()               {}
func (*GitBranchTaskEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GitBranchTaskEvent) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *GitBranchTaskEvent) GetResult() GitBranchTaskEvent_Result {
	if m != nil {
		return m.Result
	}
	return GitBranchTaskEvent_SUCCEEDED
}

func (m *GitBranchTaskEvent) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

func (m *GitBranchTaskEvent) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type ZippedContentEvent struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *ZippedContentEvent) Reset()                    { *m = ZippedContentEvent{} }
func (m *ZippedContentEvent) String() string            { return proto.CompactTextString(m) }
func (*ZippedContentEvent) ProtoMessage()               {}
func (*ZippedContentEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ZippedContentEvent) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type JobEvent struct {
	Time               *google_protobuf1.Timestamp `protobuf:"bytes,1,opt,name=time" json:"time,omitempty"`
	LogEvent           *LogEvent                   `protobuf:"bytes,2,opt,name=log_event,json=logEvent" json:"log_event,omitempty"`
	BeginCommandEvent  *BeginCommandEvent          `protobuf:"bytes,3,opt,name=begin_command_event,json=beginCommandEvent" json:"begin_command_event,omitempty"`
	CommandOutputEvent *CommandOutputEvent         `protobuf:"bytes,4,opt,name=command_output_event,json=commandOutputEvent" json:"command_output_event,omitempty"`
	EndCommandEvent    *EndCommandEvent            `protobuf:"bytes,5,opt,name=end_command_event,json=endCommandEvent" json:"end_command_event,omitempty"`
	BranchTaskEvent    *GitBranchTaskEvent         `protobuf:"bytes,6,opt,name=branch_task_event,json=branchTaskEvent" json:"branch_task_event,omitempty"`
	ZippedContent      *ZippedContentEvent         `protobuf:"bytes,7,opt,name=zipped_content,json=zippedContent" json:"zipped_content,omitempty"`
}

func (m *JobEvent) Reset()                    { *m = JobEvent{} }
func (m *JobEvent) String() string            { return proto.CompactTextString(m) }
func (*JobEvent) ProtoMessage()               {}
func (*JobEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *JobEvent) GetTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *JobEvent) GetLogEvent() *LogEvent {
	if m != nil {
		return m.LogEvent
	}
	return nil
}

func (m *JobEvent) GetBeginCommandEvent() *BeginCommandEvent {
	if m != nil {
		return m.BeginCommandEvent
	}
	return nil
}

func (m *JobEvent) GetCommandOutputEvent() *CommandOutputEvent {
	if m != nil {
		return m.CommandOutputEvent
	}
	return nil
}

func (m *JobEvent) GetEndCommandEvent() *EndCommandEvent {
	if m != nil {
		return m.EndCommandEvent
	}
	return nil
}

func (m *JobEvent) GetBranchTaskEvent() *GitBranchTaskEvent {
	if m != nil {
		return m.BranchTaskEvent
	}
	return nil
}

func (m *JobEvent) GetZippedContent() *ZippedContentEvent {
	if m != nil {
		return m.ZippedContent
	}
	return nil
}

type BuildOptions struct {
	Platform        string           `protobuf:"bytes,1,opt,name=platform" json:"platform,omitempty"`
	Targets         []string         `protobuf:"bytes,2,rep,name=targets" json:"targets,omitempty"`
	RepositoryState *RepositoryState `protobuf:"bytes,3,opt,name=repository_state,json=repositoryState" json:"repository_state,omitempty"`
}

func (m *BuildOptions) Reset()                    { *m = BuildOptions{} }
func (m *BuildOptions) String() string            { return proto.CompactTextString(m) }
func (*BuildOptions) ProtoMessage()               {}
func (*BuildOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *BuildOptions) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *BuildOptions) GetTargets() []string {
	if m != nil {
		return m.Targets
	}
	return nil
}

func (m *BuildOptions) GetRepositoryState() *RepositoryState {
	if m != nil {
		return m.RepositoryState
	}
	return nil
}

type TargetList struct {
	Target []string `protobuf:"bytes,1,rep,name=target" json:"target,omitempty"`
}

func (m *TargetList) Reset()                    { *m = TargetList{} }
func (m *TargetList) String() string            { return proto.CompactTextString(m) }
func (*TargetList) ProtoMessage()               {}
func (*TargetList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *TargetList) GetTarget() []string {
	if m != nil {
		return m.Target
	}
	return nil
}

type BranchList struct {
	Branch []string `protobuf:"bytes,1,rep,name=branch" json:"branch,omitempty"`
}

func (m *BranchList) Reset()                    { *m = BranchList{} }
func (m *BranchList) String() string            { return proto.CompactTextString(m) }
func (*BranchList) ProtoMessage()               {}
func (*BranchList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *BranchList) GetBranch() []string {
	if m != nil {
		return m.Branch
	}
	return nil
}

type RunOptions struct {
	Platform        string           `protobuf:"bytes,1,opt,name=platform" json:"platform,omitempty"`
	RepositoryState *RepositoryState `protobuf:"bytes,2,opt,name=repository_state,json=repositoryState" json:"repository_state,omitempty"`
	Dependencies    *TargetList      `protobuf:"bytes,3,opt,name=dependencies" json:"dependencies,omitempty"`
	Command         *ShellCommand    `protobuf:"bytes,4,opt,name=command" json:"command,omitempty"`
}

func (m *RunOptions) Reset()                    { *m = RunOptions{} }
func (m *RunOptions) String() string            { return proto.CompactTextString(m) }
func (*RunOptions) ProtoMessage()               {}
func (*RunOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *RunOptions) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *RunOptions) GetRepositoryState() *RepositoryState {
	if m != nil {
		return m.RepositoryState
	}
	return nil
}

func (m *RunOptions) GetDependencies() *TargetList {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

func (m *RunOptions) GetCommand() *ShellCommand {
	if m != nil {
		return m.Command
	}
	return nil
}

type ClobberOptions struct {
	Platform        string                `protobuf:"bytes,1,opt,name=platform" json:"platform,omitempty"`
	RepositoryState *RepositoryState      `protobuf:"bytes,2,opt,name=repository_state,json=repositoryState" json:"repository_state,omitempty"`
	Target          ClobberOptions_Target `protobuf:"varint,3,opt,name=target,enum=stonesthrow.ClobberOptions_Target" json:"target,omitempty"`
	Force           bool                  `protobuf:"varint,4,opt,name=force" json:"force,omitempty"`
}

func (m *ClobberOptions) Reset()                    { *m = ClobberOptions{} }
func (m *ClobberOptions) String() string            { return proto.CompactTextString(m) }
func (*ClobberOptions) ProtoMessage()               {}
func (*ClobberOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *ClobberOptions) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *ClobberOptions) GetRepositoryState() *RepositoryState {
	if m != nil {
		return m.RepositoryState
	}
	return nil
}

func (m *ClobberOptions) GetTarget() ClobberOptions_Target {
	if m != nil {
		return m.Target
	}
	return ClobberOptions_SOURCE
}

func (m *ClobberOptions) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

type PingOptions struct {
	Ping string `protobuf:"bytes,1,opt,name=ping" json:"ping,omitempty"`
}

func (m *PingOptions) Reset()                    { *m = PingOptions{} }
func (m *PingOptions) String() string            { return proto.CompactTextString(m) }
func (*PingOptions) ProtoMessage()               {}
func (*PingOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *PingOptions) GetPing() string {
	if m != nil {
		return m.Ping
	}
	return ""
}

type PingResult struct {
	Pong string `protobuf:"bytes,1,opt,name=pong" json:"pong,omitempty"`
}

func (m *PingResult) Reset()                    { *m = PingResult{} }
func (m *PingResult) String() string            { return proto.CompactTextString(m) }
func (*PingResult) ProtoMessage()               {}
func (*PingResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *PingResult) GetPong() string {
	if m != nil {
		return m.Pong
	}
	return ""
}

type FetchFileOptions struct {
	RelativePath string `protobuf:"bytes,1,opt,name=relative_path,json=relativePath" json:"relative_path,omitempty"`
	FilenameGlob string `protobuf:"bytes,2,opt,name=filename_glob,json=filenameGlob" json:"filename_glob,omitempty"`
	Recurse      bool   `protobuf:"varint,3,opt,name=recurse" json:"recurse,omitempty"`
}

func (m *FetchFileOptions) Reset()                    { *m = FetchFileOptions{} }
func (m *FetchFileOptions) String() string            { return proto.CompactTextString(m) }
func (*FetchFileOptions) ProtoMessage()               {}
func (*FetchFileOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *FetchFileOptions) GetRelativePath() string {
	if m != nil {
		return m.RelativePath
	}
	return ""
}

func (m *FetchFileOptions) GetFilenameGlob() string {
	if m != nil {
		return m.FilenameGlob
	}
	return ""
}

func (m *FetchFileOptions) GetRecurse() bool {
	if m != nil {
		return m.Recurse
	}
	return false
}

type BranchConfigOptions struct {
	BranchSpec       string `protobuf:"bytes,1,opt,name=branch_spec,json=branchSpec" json:"branch_spec,omitempty"`
	IncludeGitConfig bool   `protobuf:"varint,2,opt,name=include_git_config,json=includeGitConfig" json:"include_git_config,omitempty"`
}

func (m *BranchConfigOptions) Reset()                    { *m = BranchConfigOptions{} }
func (m *BranchConfigOptions) String() string            { return proto.CompactTextString(m) }
func (*BranchConfigOptions) ProtoMessage()               {}
func (*BranchConfigOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *BranchConfigOptions) GetBranchSpec() string {
	if m != nil {
		return m.BranchSpec
	}
	return ""
}

func (m *BranchConfigOptions) GetIncludeGitConfig() bool {
	if m != nil {
		return m.IncludeGitConfig
	}
	return false
}

func init() {
	proto.RegisterType((*ShellCommand)(nil), "stonesthrow.ShellCommand")
	proto.RegisterType((*RepositoryState)(nil), "stonesthrow.RepositoryState")
	proto.RegisterType((*RunState)(nil), "stonesthrow.RunState")
	proto.RegisterType((*BuilderJob)(nil), "stonesthrow.BuilderJob")
	proto.RegisterType((*BuilderJobs)(nil), "stonesthrow.BuilderJobs")
	proto.RegisterType((*GitRepositoryInfo)(nil), "stonesthrow.GitRepositoryInfo")
	proto.RegisterType((*GitRepositoryInfo_Branch)(nil), "stonesthrow.GitRepositoryInfo.Branch")
	proto.RegisterType((*GitRepositoryInfo_Upstream)(nil), "stonesthrow.GitRepositoryInfo.Upstream")
	proto.RegisterType((*LogEvent)(nil), "stonesthrow.LogEvent")
	proto.RegisterType((*BeginCommandEvent)(nil), "stonesthrow.BeginCommandEvent")
	proto.RegisterType((*CommandOutputEvent)(nil), "stonesthrow.CommandOutputEvent")
	proto.RegisterType((*EndCommandEvent)(nil), "stonesthrow.EndCommandEvent")
	proto.RegisterType((*GitBranchTaskEvent)(nil), "stonesthrow.GitBranchTaskEvent")
	proto.RegisterType((*ZippedContentEvent)(nil), "stonesthrow.ZippedContentEvent")
	proto.RegisterType((*JobEvent)(nil), "stonesthrow.JobEvent")
	proto.RegisterType((*BuildOptions)(nil), "stonesthrow.BuildOptions")
	proto.RegisterType((*TargetList)(nil), "stonesthrow.TargetList")
	proto.RegisterType((*BranchList)(nil), "stonesthrow.BranchList")
	proto.RegisterType((*RunOptions)(nil), "stonesthrow.RunOptions")
	proto.RegisterType((*ClobberOptions)(nil), "stonesthrow.ClobberOptions")
	proto.RegisterType((*PingOptions)(nil), "stonesthrow.PingOptions")
	proto.RegisterType((*PingResult)(nil), "stonesthrow.PingResult")
	proto.RegisterType((*FetchFileOptions)(nil), "stonesthrow.FetchFileOptions")
	proto.RegisterType((*BranchConfigOptions)(nil), "stonesthrow.BranchConfigOptions")
	proto.RegisterEnum("stonesthrow.LogEvent_Severity", LogEvent_Severity_name, LogEvent_Severity_value)
	proto.RegisterEnum("stonesthrow.CommandOutputEvent_Stream", CommandOutputEvent_Stream_name, CommandOutputEvent_Stream_value)
	proto.RegisterEnum("stonesthrow.GitBranchTaskEvent_Result", GitBranchTaskEvent_Result_name, GitBranchTaskEvent_Result_value)
	proto.RegisterEnum("stonesthrow.ClobberOptions_Target", ClobberOptions_Target_name, ClobberOptions_Target_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PlatformBuildHost service

type PlatformBuildHostClient interface {
	Build(ctx context.Context, in *BuildOptions, opts ...grpc.CallOption) (PlatformBuildHost_BuildClient, error)
	Run(ctx context.Context, in *RunOptions, opts ...grpc.CallOption) (PlatformBuildHost_RunClient, error)
	Clobber(ctx context.Context, in *ClobberOptions, opts ...grpc.CallOption) (PlatformBuildHost_ClobberClient, error)
	Clean(ctx context.Context, in *BuildOptions, opts ...grpc.CallOption) (PlatformBuildHost_CleanClient, error)
	Prepare(ctx context.Context, in *BuildOptions, opts ...grpc.CallOption) (PlatformBuildHost_PrepareClient, error)
	ListTargets(ctx context.Context, in *BuildOptions, opts ...grpc.CallOption) (*TargetList, error)
	FetchFile(ctx context.Context, in *FetchFileOptions, opts ...grpc.CallOption) (PlatformBuildHost_FetchFileClient, error)
}

type platformBuildHostClient struct {
	cc *grpc.ClientConn
}

func NewPlatformBuildHostClient(cc *grpc.ClientConn) PlatformBuildHostClient {
	return &platformBuildHostClient{cc}
}

func (c *platformBuildHostClient) Build(ctx context.Context, in *BuildOptions, opts ...grpc.CallOption) (PlatformBuildHost_BuildClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PlatformBuildHost_serviceDesc.Streams[0], c.cc, "/stonesthrow.PlatformBuildHost/Build", opts...)
	if err != nil {
		return nil, err
	}
	x := &platformBuildHostBuildClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PlatformBuildHost_BuildClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type platformBuildHostBuildClient struct {
	grpc.ClientStream
}

func (x *platformBuildHostBuildClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *platformBuildHostClient) Run(ctx context.Context, in *RunOptions, opts ...grpc.CallOption) (PlatformBuildHost_RunClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PlatformBuildHost_serviceDesc.Streams[1], c.cc, "/stonesthrow.PlatformBuildHost/Run", opts...)
	if err != nil {
		return nil, err
	}
	x := &platformBuildHostRunClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PlatformBuildHost_RunClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type platformBuildHostRunClient struct {
	grpc.ClientStream
}

func (x *platformBuildHostRunClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *platformBuildHostClient) Clobber(ctx context.Context, in *ClobberOptions, opts ...grpc.CallOption) (PlatformBuildHost_ClobberClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PlatformBuildHost_serviceDesc.Streams[2], c.cc, "/stonesthrow.PlatformBuildHost/Clobber", opts...)
	if err != nil {
		return nil, err
	}
	x := &platformBuildHostClobberClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PlatformBuildHost_ClobberClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type platformBuildHostClobberClient struct {
	grpc.ClientStream
}

func (x *platformBuildHostClobberClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *platformBuildHostClient) Clean(ctx context.Context, in *BuildOptions, opts ...grpc.CallOption) (PlatformBuildHost_CleanClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PlatformBuildHost_serviceDesc.Streams[3], c.cc, "/stonesthrow.PlatformBuildHost/Clean", opts...)
	if err != nil {
		return nil, err
	}
	x := &platformBuildHostCleanClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PlatformBuildHost_CleanClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type platformBuildHostCleanClient struct {
	grpc.ClientStream
}

func (x *platformBuildHostCleanClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *platformBuildHostClient) Prepare(ctx context.Context, in *BuildOptions, opts ...grpc.CallOption) (PlatformBuildHost_PrepareClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PlatformBuildHost_serviceDesc.Streams[4], c.cc, "/stonesthrow.PlatformBuildHost/Prepare", opts...)
	if err != nil {
		return nil, err
	}
	x := &platformBuildHostPrepareClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PlatformBuildHost_PrepareClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type platformBuildHostPrepareClient struct {
	grpc.ClientStream
}

func (x *platformBuildHostPrepareClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *platformBuildHostClient) ListTargets(ctx context.Context, in *BuildOptions, opts ...grpc.CallOption) (*TargetList, error) {
	out := new(TargetList)
	err := grpc.Invoke(ctx, "/stonesthrow.PlatformBuildHost/ListTargets", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformBuildHostClient) FetchFile(ctx context.Context, in *FetchFileOptions, opts ...grpc.CallOption) (PlatformBuildHost_FetchFileClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PlatformBuildHost_serviceDesc.Streams[5], c.cc, "/stonesthrow.PlatformBuildHost/FetchFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &platformBuildHostFetchFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PlatformBuildHost_FetchFileClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type platformBuildHostFetchFileClient struct {
	grpc.ClientStream
}

func (x *platformBuildHostFetchFileClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for PlatformBuildHost service

type PlatformBuildHostServer interface {
	Build(*BuildOptions, PlatformBuildHost_BuildServer) error
	Run(*RunOptions, PlatformBuildHost_RunServer) error
	Clobber(*ClobberOptions, PlatformBuildHost_ClobberServer) error
	Clean(*BuildOptions, PlatformBuildHost_CleanServer) error
	Prepare(*BuildOptions, PlatformBuildHost_PrepareServer) error
	ListTargets(context.Context, *BuildOptions) (*TargetList, error)
	FetchFile(*FetchFileOptions, PlatformBuildHost_FetchFileServer) error
}

func RegisterPlatformBuildHostServer(s *grpc.Server, srv PlatformBuildHostServer) {
	s.RegisterService(&_PlatformBuildHost_serviceDesc, srv)
}

func _PlatformBuildHost_Build_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BuildOptions)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlatformBuildHostServer).Build(m, &platformBuildHostBuildServer{stream})
}

type PlatformBuildHost_BuildServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type platformBuildHostBuildServer struct {
	grpc.ServerStream
}

func (x *platformBuildHostBuildServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _PlatformBuildHost_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunOptions)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlatformBuildHostServer).Run(m, &platformBuildHostRunServer{stream})
}

type PlatformBuildHost_RunServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type platformBuildHostRunServer struct {
	grpc.ServerStream
}

func (x *platformBuildHostRunServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _PlatformBuildHost_Clobber_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClobberOptions)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlatformBuildHostServer).Clobber(m, &platformBuildHostClobberServer{stream})
}

type PlatformBuildHost_ClobberServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type platformBuildHostClobberServer struct {
	grpc.ServerStream
}

func (x *platformBuildHostClobberServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _PlatformBuildHost_Clean_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BuildOptions)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlatformBuildHostServer).Clean(m, &platformBuildHostCleanServer{stream})
}

type PlatformBuildHost_CleanServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type platformBuildHostCleanServer struct {
	grpc.ServerStream
}

func (x *platformBuildHostCleanServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _PlatformBuildHost_Prepare_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BuildOptions)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlatformBuildHostServer).Prepare(m, &platformBuildHostPrepareServer{stream})
}

type PlatformBuildHost_PrepareServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type platformBuildHostPrepareServer struct {
	grpc.ServerStream
}

func (x *platformBuildHostPrepareServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _PlatformBuildHost_ListTargets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformBuildHostServer).ListTargets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stonesthrow.PlatformBuildHost/ListTargets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformBuildHostServer).ListTargets(ctx, req.(*BuildOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformBuildHost_FetchFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchFileOptions)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlatformBuildHostServer).FetchFile(m, &platformBuildHostFetchFileServer{stream})
}

type PlatformBuildHost_FetchFileServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type platformBuildHostFetchFileServer struct {
	grpc.ServerStream
}

func (x *platformBuildHostFetchFileServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

var _PlatformBuildHost_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stonesthrow.PlatformBuildHost",
	HandlerType: (*PlatformBuildHostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTargets",
			Handler:    _PlatformBuildHost_ListTargets_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Build",
			Handler:       _PlatformBuildHost_Build_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Run",
			Handler:       _PlatformBuildHost_Run_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Clobber",
			Handler:       _PlatformBuildHost_Clobber_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Clean",
			Handler:       _PlatformBuildHost_Clean_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Prepare",
			Handler:       _PlatformBuildHost_Prepare_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FetchFile",
			Handler:       _PlatformBuildHost_FetchFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "st.proto",
}

// Client API for RepositoryHost service

type RepositoryHostClient interface {
	GetBranchConfig(ctx context.Context, in *BranchConfigOptions, opts ...grpc.CallOption) (*GitRepositoryInfo, error)
	SetBranchConfig(ctx context.Context, in *GitRepositoryInfo, opts ...grpc.CallOption) (RepositoryHost_SetBranchConfigClient, error)
	PullFromUpstream(ctx context.Context, in *BranchList, opts ...grpc.CallOption) (RepositoryHost_PullFromUpstreamClient, error)
	PushToUpstream(ctx context.Context, in *BranchList, opts ...grpc.CallOption) (RepositoryHost_PushToUpstreamClient, error)
	Status(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (RepositoryHost_StatusClient, error)
	SyncLocal(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (RepositoryHost_SyncLocalClient, error)
	SyncRemote(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (RepositoryHost_SyncRemoteClient, error)
	PrepareForReceive(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (RepositoryHost_PrepareForReceiveClient, error)
	RebaseUpdate(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (RepositoryHost_RebaseUpdateClient, error)
	FetchFile(ctx context.Context, in *FetchFileOptions, opts ...grpc.CallOption) (RepositoryHost_FetchFileClient, error)
}

type repositoryHostClient struct {
	cc *grpc.ClientConn
}

func NewRepositoryHostClient(cc *grpc.ClientConn) RepositoryHostClient {
	return &repositoryHostClient{cc}
}

func (c *repositoryHostClient) GetBranchConfig(ctx context.Context, in *BranchConfigOptions, opts ...grpc.CallOption) (*GitRepositoryInfo, error) {
	out := new(GitRepositoryInfo)
	err := grpc.Invoke(ctx, "/stonesthrow.RepositoryHost/GetBranchConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryHostClient) SetBranchConfig(ctx context.Context, in *GitRepositoryInfo, opts ...grpc.CallOption) (RepositoryHost_SetBranchConfigClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RepositoryHost_serviceDesc.Streams[0], c.cc, "/stonesthrow.RepositoryHost/SetBranchConfig", opts...)
	if err != nil {
		return nil, err
	}
	x := &repositoryHostSetBranchConfigClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RepositoryHost_SetBranchConfigClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type repositoryHostSetBranchConfigClient struct {
	grpc.ClientStream
}

func (x *repositoryHostSetBranchConfigClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *repositoryHostClient) PullFromUpstream(ctx context.Context, in *BranchList, opts ...grpc.CallOption) (RepositoryHost_PullFromUpstreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RepositoryHost_serviceDesc.Streams[1], c.cc, "/stonesthrow.RepositoryHost/PullFromUpstream", opts...)
	if err != nil {
		return nil, err
	}
	x := &repositoryHostPullFromUpstreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RepositoryHost_PullFromUpstreamClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type repositoryHostPullFromUpstreamClient struct {
	grpc.ClientStream
}

func (x *repositoryHostPullFromUpstreamClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *repositoryHostClient) PushToUpstream(ctx context.Context, in *BranchList, opts ...grpc.CallOption) (RepositoryHost_PushToUpstreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RepositoryHost_serviceDesc.Streams[2], c.cc, "/stonesthrow.RepositoryHost/PushToUpstream", opts...)
	if err != nil {
		return nil, err
	}
	x := &repositoryHostPushToUpstreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RepositoryHost_PushToUpstreamClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type repositoryHostPushToUpstreamClient struct {
	grpc.ClientStream
}

func (x *repositoryHostPushToUpstreamClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *repositoryHostClient) Status(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (RepositoryHost_StatusClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RepositoryHost_serviceDesc.Streams[3], c.cc, "/stonesthrow.RepositoryHost/Status", opts...)
	if err != nil {
		return nil, err
	}
	x := &repositoryHostStatusClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RepositoryHost_StatusClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type repositoryHostStatusClient struct {
	grpc.ClientStream
}

func (x *repositoryHostStatusClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *repositoryHostClient) SyncLocal(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (RepositoryHost_SyncLocalClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RepositoryHost_serviceDesc.Streams[4], c.cc, "/stonesthrow.RepositoryHost/SyncLocal", opts...)
	if err != nil {
		return nil, err
	}
	x := &repositoryHostSyncLocalClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RepositoryHost_SyncLocalClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type repositoryHostSyncLocalClient struct {
	grpc.ClientStream
}

func (x *repositoryHostSyncLocalClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *repositoryHostClient) SyncRemote(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (RepositoryHost_SyncRemoteClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RepositoryHost_serviceDesc.Streams[5], c.cc, "/stonesthrow.RepositoryHost/SyncRemote", opts...)
	if err != nil {
		return nil, err
	}
	x := &repositoryHostSyncRemoteClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RepositoryHost_SyncRemoteClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type repositoryHostSyncRemoteClient struct {
	grpc.ClientStream
}

func (x *repositoryHostSyncRemoteClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *repositoryHostClient) PrepareForReceive(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (RepositoryHost_PrepareForReceiveClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RepositoryHost_serviceDesc.Streams[6], c.cc, "/stonesthrow.RepositoryHost/PrepareForReceive", opts...)
	if err != nil {
		return nil, err
	}
	x := &repositoryHostPrepareForReceiveClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RepositoryHost_PrepareForReceiveClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type repositoryHostPrepareForReceiveClient struct {
	grpc.ClientStream
}

func (x *repositoryHostPrepareForReceiveClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *repositoryHostClient) RebaseUpdate(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (RepositoryHost_RebaseUpdateClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RepositoryHost_serviceDesc.Streams[7], c.cc, "/stonesthrow.RepositoryHost/RebaseUpdate", opts...)
	if err != nil {
		return nil, err
	}
	x := &repositoryHostRebaseUpdateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RepositoryHost_RebaseUpdateClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type repositoryHostRebaseUpdateClient struct {
	grpc.ClientStream
}

func (x *repositoryHostRebaseUpdateClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *repositoryHostClient) FetchFile(ctx context.Context, in *FetchFileOptions, opts ...grpc.CallOption) (RepositoryHost_FetchFileClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RepositoryHost_serviceDesc.Streams[8], c.cc, "/stonesthrow.RepositoryHost/FetchFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &repositoryHostFetchFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RepositoryHost_FetchFileClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type repositoryHostFetchFileClient struct {
	grpc.ClientStream
}

func (x *repositoryHostFetchFileClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for RepositoryHost service

type RepositoryHostServer interface {
	GetBranchConfig(context.Context, *BranchConfigOptions) (*GitRepositoryInfo, error)
	SetBranchConfig(*GitRepositoryInfo, RepositoryHost_SetBranchConfigServer) error
	PullFromUpstream(*BranchList, RepositoryHost_PullFromUpstreamServer) error
	PushToUpstream(*BranchList, RepositoryHost_PushToUpstreamServer) error
	Status(*RepositoryState, RepositoryHost_StatusServer) error
	SyncLocal(*RepositoryState, RepositoryHost_SyncLocalServer) error
	SyncRemote(*RepositoryState, RepositoryHost_SyncRemoteServer) error
	PrepareForReceive(*RepositoryState, RepositoryHost_PrepareForReceiveServer) error
	RebaseUpdate(*RepositoryState, RepositoryHost_RebaseUpdateServer) error
	FetchFile(*FetchFileOptions, RepositoryHost_FetchFileServer) error
}

func RegisterRepositoryHostServer(s *grpc.Server, srv RepositoryHostServer) {
	s.RegisterService(&_RepositoryHost_serviceDesc, srv)
}

func _RepositoryHost_GetBranchConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BranchConfigOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryHostServer).GetBranchConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stonesthrow.RepositoryHost/GetBranchConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryHostServer).GetBranchConfig(ctx, req.(*BranchConfigOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepositoryHost_SetBranchConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GitRepositoryInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RepositoryHostServer).SetBranchConfig(m, &repositoryHostSetBranchConfigServer{stream})
}

type RepositoryHost_SetBranchConfigServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type repositoryHostSetBranchConfigServer struct {
	grpc.ServerStream
}

func (x *repositoryHostSetBranchConfigServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _RepositoryHost_PullFromUpstream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BranchList)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RepositoryHostServer).PullFromUpstream(m, &repositoryHostPullFromUpstreamServer{stream})
}

type RepositoryHost_PullFromUpstreamServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type repositoryHostPullFromUpstreamServer struct {
	grpc.ServerStream
}

func (x *repositoryHostPullFromUpstreamServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _RepositoryHost_PushToUpstream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BranchList)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RepositoryHostServer).PushToUpstream(m, &repositoryHostPushToUpstreamServer{stream})
}

type RepositoryHost_PushToUpstreamServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type repositoryHostPushToUpstreamServer struct {
	grpc.ServerStream
}

func (x *repositoryHostPushToUpstreamServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _RepositoryHost_Status_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RepositoryState)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RepositoryHostServer).Status(m, &repositoryHostStatusServer{stream})
}

type RepositoryHost_StatusServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type repositoryHostStatusServer struct {
	grpc.ServerStream
}

func (x *repositoryHostStatusServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _RepositoryHost_SyncLocal_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RepositoryState)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RepositoryHostServer).SyncLocal(m, &repositoryHostSyncLocalServer{stream})
}

type RepositoryHost_SyncLocalServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type repositoryHostSyncLocalServer struct {
	grpc.ServerStream
}

func (x *repositoryHostSyncLocalServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _RepositoryHost_SyncRemote_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RepositoryState)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RepositoryHostServer).SyncRemote(m, &repositoryHostSyncRemoteServer{stream})
}

type RepositoryHost_SyncRemoteServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type repositoryHostSyncRemoteServer struct {
	grpc.ServerStream
}

func (x *repositoryHostSyncRemoteServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _RepositoryHost_PrepareForReceive_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RepositoryState)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RepositoryHostServer).PrepareForReceive(m, &repositoryHostPrepareForReceiveServer{stream})
}

type RepositoryHost_PrepareForReceiveServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type repositoryHostPrepareForReceiveServer struct {
	grpc.ServerStream
}

func (x *repositoryHostPrepareForReceiveServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _RepositoryHost_RebaseUpdate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RepositoryState)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RepositoryHostServer).RebaseUpdate(m, &repositoryHostRebaseUpdateServer{stream})
}

type RepositoryHost_RebaseUpdateServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type repositoryHostRebaseUpdateServer struct {
	grpc.ServerStream
}

func (x *repositoryHostRebaseUpdateServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _RepositoryHost_FetchFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchFileOptions)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RepositoryHostServer).FetchFile(m, &repositoryHostFetchFileServer{stream})
}

type RepositoryHost_FetchFileServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type repositoryHostFetchFileServer struct {
	grpc.ServerStream
}

func (x *repositoryHostFetchFileServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

var _RepositoryHost_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stonesthrow.RepositoryHost",
	HandlerType: (*RepositoryHostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBranchConfig",
			Handler:    _RepositoryHost_GetBranchConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SetBranchConfig",
			Handler:       _RepositoryHost_SetBranchConfig_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PullFromUpstream",
			Handler:       _RepositoryHost_PullFromUpstream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PushToUpstream",
			Handler:       _RepositoryHost_PushToUpstream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Status",
			Handler:       _RepositoryHost_Status_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SyncLocal",
			Handler:       _RepositoryHost_SyncLocal_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SyncRemote",
			Handler:       _RepositoryHost_SyncRemote_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PrepareForReceive",
			Handler:       _RepositoryHost_PrepareForReceive_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RebaseUpdate",
			Handler:       _RepositoryHost_RebaseUpdate_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FetchFile",
			Handler:       _RepositoryHost_FetchFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "st.proto",
}

// Client API for ServiceHost service

type ServiceHostClient interface {
	Ping(ctx context.Context, in *PingOptions, opts ...grpc.CallOption) (*PingResult, error)
	ListJobs(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (*BuilderJobs, error)
	KillJobs(ctx context.Context, in *BuilderJobs, opts ...grpc.CallOption) (ServiceHost_KillJobsClient, error)
	Shutdown(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (ServiceHost_ShutdownClient, error)
	SelfUpdate(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (ServiceHost_SelfUpdateClient, error)
}

type serviceHostClient struct {
	cc *grpc.ClientConn
}

func NewServiceHostClient(cc *grpc.ClientConn) ServiceHostClient {
	return &serviceHostClient{cc}
}

func (c *serviceHostClient) Ping(ctx context.Context, in *PingOptions, opts ...grpc.CallOption) (*PingResult, error) {
	out := new(PingResult)
	err := grpc.Invoke(ctx, "/stonesthrow.ServiceHost/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceHostClient) ListJobs(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (*BuilderJobs, error) {
	out := new(BuilderJobs)
	err := grpc.Invoke(ctx, "/stonesthrow.ServiceHost/ListJobs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceHostClient) KillJobs(ctx context.Context, in *BuilderJobs, opts ...grpc.CallOption) (ServiceHost_KillJobsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ServiceHost_serviceDesc.Streams[0], c.cc, "/stonesthrow.ServiceHost/KillJobs", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceHostKillJobsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ServiceHost_KillJobsClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type serviceHostKillJobsClient struct {
	grpc.ClientStream
}

func (x *serviceHostKillJobsClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serviceHostClient) Shutdown(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (ServiceHost_ShutdownClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ServiceHost_serviceDesc.Streams[1], c.cc, "/stonesthrow.ServiceHost/Shutdown", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceHostShutdownClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ServiceHost_ShutdownClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type serviceHostShutdownClient struct {
	grpc.ClientStream
}

func (x *serviceHostShutdownClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serviceHostClient) SelfUpdate(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (ServiceHost_SelfUpdateClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ServiceHost_serviceDesc.Streams[2], c.cc, "/stonesthrow.ServiceHost/SelfUpdate", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceHostSelfUpdateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ServiceHost_SelfUpdateClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type serviceHostSelfUpdateClient struct {
	grpc.ClientStream
}

func (x *serviceHostSelfUpdateClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for ServiceHost service

type ServiceHostServer interface {
	Ping(context.Context, *PingOptions) (*PingResult, error)
	ListJobs(context.Context, *RepositoryState) (*BuilderJobs, error)
	KillJobs(*BuilderJobs, ServiceHost_KillJobsServer) error
	Shutdown(*RepositoryState, ServiceHost_ShutdownServer) error
	SelfUpdate(*RepositoryState, ServiceHost_SelfUpdateServer) error
}

func RegisterServiceHostServer(s *grpc.Server, srv ServiceHostServer) {
	s.RegisterService(&_ServiceHost_serviceDesc, srv)
}

func _ServiceHost_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceHostServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stonesthrow.ServiceHost/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceHostServer).Ping(ctx, req.(*PingOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceHost_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepositoryState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceHostServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stonesthrow.ServiceHost/ListJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceHostServer).ListJobs(ctx, req.(*RepositoryState))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceHost_KillJobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BuilderJobs)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceHostServer).KillJobs(m, &serviceHostKillJobsServer{stream})
}

type ServiceHost_KillJobsServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type serviceHostKillJobsServer struct {
	grpc.ServerStream
}

func (x *serviceHostKillJobsServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _ServiceHost_Shutdown_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RepositoryState)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceHostServer).Shutdown(m, &serviceHostShutdownServer{stream})
}

type ServiceHost_ShutdownServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type serviceHostShutdownServer struct {
	grpc.ServerStream
}

func (x *serviceHostShutdownServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _ServiceHost_SelfUpdate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RepositoryState)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceHostServer).SelfUpdate(m, &serviceHostSelfUpdateServer{stream})
}

type ServiceHost_SelfUpdateServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type serviceHostSelfUpdateServer struct {
	grpc.ServerStream
}

func (x *serviceHostSelfUpdateServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

var _ServiceHost_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stonesthrow.ServiceHost",
	HandlerType: (*ServiceHostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ServiceHost_Ping_Handler,
		},
		{
			MethodName: "ListJobs",
			Handler:    _ServiceHost_ListJobs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "KillJobs",
			Handler:       _ServiceHost_KillJobs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Shutdown",
			Handler:       _ServiceHost_Shutdown_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SelfUpdate",
			Handler:       _ServiceHost_SelfUpdate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "st.proto",
}

func init() { proto.RegisterFile("st.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1674 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0xcd, 0x72, 0x23, 0x49,
	0x11, 0x9e, 0xd6, 0x9f, 0x5b, 0x29, 0x8f, 0x2d, 0xd7, 0x2e, 0x3b, 0x1a, 0xed, 0x32, 0x63, 0x7a,
	0x81, 0x1d, 0x58, 0x42, 0x0b, 0xde, 0xe0, 0x67, 0x3c, 0xb1, 0x6c, 0x8c, 0x65, 0xd9, 0x33, 0xb3,
	0xc3, 0xda, 0x94, 0x24, 0x0e, 0x7b, 0x51, 0xb4, 0xba, 0x4b, 0x52, 0x33, 0xad, 0xaa, 0x8e, 0xaa,
	0x6a, 0x6d, 0x78, 0x9f, 0x80, 0x20, 0x82, 0x0b, 0x07, 0x82, 0x27, 0xe0, 0x4d, 0xb8, 0x72, 0xe1,
	0xcc, 0x05, 0x4e, 0xdc, 0x78, 0x04, 0xa2, 0x7e, 0x5a, 0x52, 0x4b, 0xb6, 0xec, 0xd0, 0x10, 0xdc,
	0xaa, 0xb2, 0x33, 0x3f, 0x65, 0x66, 0x7d, 0xf9, 0x63, 0x83, 0x2b, 0x64, 0x2b, 0xe1, 0x4c, 0x32,
	0x54, 0x13, 0x92, 0x51, 0x22, 0xe4, 0x84, 0xb3, 0xaf, 0x9b, 0x8f, 0xc6, 0x8c, 0x8d, 0x63, 0xf2,
	0x89, 0xfe, 0x34, 0x4c, 0x47, 0x9f, 0x84, 0x29, 0xf7, 0x65, 0xc4, 0xa8, 0x51, 0x6e, 0x3e, 0x5e,
	0xfd, 0x2e, 0xa3, 0x29, 0x11, 0xd2, 0x9f, 0x26, 0x46, 0xc1, 0xfb, 0x0a, 0x76, 0xbb, 0x13, 0x12,
	0xc7, 0x6d, 0x36, 0x9d, 0xfa, 0x34, 0x44, 0x0d, 0xd8, 0x09, 0xcc, 0xb1, 0xe1, 0x1c, 0x16, 0x9f,
	0x54, 0x71, 0x76, 0x45, 0x1f, 0x40, 0x35, 0x8c, 0x38, 0x09, 0x24, 0xe3, 0x57, 0x8d, 0xc2, 0xa1,
	0xf3, 0xa4, 0x8a, 0x17, 0x02, 0x84, 0xa0, 0x34, 0x61, 0x42, 0x36, 0x8a, 0xfa, 0x83, 0x3e, 0x7b,
	0xbf, 0x82, 0x7d, 0x4c, 0x12, 0x26, 0x22, 0xa5, 0xd1, 0x95, 0xbe, 0x24, 0xe8, 0x11, 0x00, 0x9f,
	0x8b, 0x2c, 0xca, 0x92, 0x04, 0x35, 0xc1, 0xe5, 0x64, 0x16, 0x89, 0x88, 0x51, 0x0b, 0x35, 0xbf,
	0x7b, 0x7f, 0x72, 0xc0, 0xc5, 0x29, 0x35, 0x40, 0x4f, 0x01, 0x84, 0xf4, 0xb9, 0x1c, 0xa8, 0x80,
	0x1a, 0xce, 0xa1, 0xf3, 0xa4, 0x76, 0xd4, 0x6c, 0x99, 0x68, 0x5b, 0x59, 0xb4, 0xad, 0x5e, 0x16,
	0x2d, 0xae, 0x6a, 0x6d, 0x75, 0x57, 0x21, 0xf2, 0x94, 0xd2, 0x88, 0x8e, 0xb5, 0x03, 0x2e, 0xce,
	0xae, 0xe8, 0xa7, 0xe0, 0x12, 0x1a, 0x1a, 0xc8, 0xe2, 0xad, 0x90, 0x3b, 0x84, 0x86, 0xea, 0xe6,
	0xfd, 0xd3, 0x01, 0x38, 0x49, 0xa3, 0x38, 0x24, 0xfc, 0x15, 0x1b, 0xa2, 0x4f, 0x97, 0x53, 0xa8,
	0x40, 0x1e, 0xb6, 0x96, 0x9e, 0xac, 0xb5, 0x9c, 0xee, 0x45, 0x76, 0x3f, 0x86, 0xb2, 0x50, 0x81,
	0x69, 0x97, 0x6a, 0x47, 0xdf, 0xca, 0x99, 0x64, 0x51, 0x63, 0xa3, 0x83, 0x8e, 0xa1, 0x26, 0xae,
	0x84, 0x24, 0xd3, 0x65, 0x57, 0x1f, 0xae, 0xb9, 0x7a, 0x6a, 0xb9, 0x80, 0xc1, 0x68, 0xeb, 0xe8,
	0x7f, 0x06, 0xd5, 0x54, 0x10, 0x6e, 0x2c, 0x4b, 0xb7, 0x59, 0xba, 0x4a, 0x57, 0x07, 0x79, 0x0c,
	0xb5, 0x45, 0x8c, 0x02, 0x7d, 0x0c, 0xa5, 0xdf, 0xb2, 0xa1, 0xd0, 0x24, 0xa9, 0x1d, 0x3d, 0xc8,
	0xb9, 0xbb, 0xd0, 0xc3, 0x5a, 0xc9, 0xfb, 0x7d, 0x09, 0x0e, 0xce, 0x23, 0xb9, 0x20, 0xc3, 0x4b,
	0x3a, 0x62, 0xe8, 0x39, 0xb8, 0x43, 0xee, 0xd3, 0x60, 0x42, 0x32, 0x98, 0xef, 0xe5, 0x60, 0xd6,
	0x2c, 0x5a, 0x27, 0x5a, 0x1d, 0xcf, 0xcd, 0x50, 0x07, 0xaa, 0x69, 0x22, 0x24, 0x27, 0xfe, 0x54,
	0x34, 0x0a, 0x1a, 0xe3, 0xa3, 0x5b, 0x30, 0xfa, 0x56, 0x1f, 0x2f, 0x2c, 0x9b, 0x7f, 0x2c, 0x40,
	0xc5, 0x60, 0x2b, 0x1e, 0x53, 0xdf, 0x32, 0xaa, 0x8a, 0xf5, 0x39, 0x47, 0xca, 0x42, 0x9e, 0x94,
	0xe8, 0x23, 0xd8, 0xcf, 0xce, 0x62, 0xe0, 0x4f, 0x88, 0x1f, 0xea, 0xe7, 0x28, 0xe3, 0xbd, 0xb9,
	0xf8, 0xb9, 0x92, 0xa2, 0x1f, 0x40, 0x7d, 0xa1, 0x38, 0x24, 0x93, 0x88, 0x86, 0x3a, 0xfd, 0x65,
	0xbc, 0x00, 0x38, 0xd1, 0x62, 0xf4, 0x12, 0x2a, 0x01, 0xa3, 0xa3, 0x68, 0xdc, 0x28, 0xeb, 0x90,
	0x7e, 0x72, 0xa7, 0xb4, 0xb4, 0xda, 0xda, 0xa6, 0x43, 0x25, 0xbf, 0xc2, 0x16, 0xa0, 0xf9, 0x14,
	0x6a, 0x4b, 0x62, 0x54, 0x87, 0xe2, 0x1b, 0x72, 0x65, 0x83, 0x53, 0x47, 0xf4, 0x2e, 0x94, 0x67,
	0x7e, 0x9c, 0x12, 0x1b, 0x98, 0xb9, 0x1c, 0x17, 0x7e, 0xe1, 0x34, 0x7f, 0x03, 0x6e, 0x96, 0xab,
	0x6b, 0xb3, 0xf2, 0x10, 0xdc, 0x24, 0x15, 0x93, 0x41, 0xca, 0x63, 0x6b, 0xbc, 0xa3, 0xee, 0x7d,
	0x1e, 0xa3, 0xf7, 0xa1, 0x3a, 0x22, 0x32, 0x30, 0xdf, 0x6c, 0x19, 0x6b, 0x41, 0x9f, 0xc7, 0xde,
	0x9f, 0x1d, 0x70, 0x5f, 0xb3, 0x71, 0x67, 0x46, 0xa8, 0x9c, 0xb7, 0x0d, 0x67, 0xd1, 0x36, 0x94,
	0x93, 0x53, 0x31, 0xb6, 0x98, 0xea, 0x88, 0x8e, 0xc1, 0x15, 0x64, 0x46, 0x78, 0x24, 0xaf, 0x34,
	0xdc, 0xde, 0xd1, 0xa3, 0x5c, 0x4a, 0x32, 0xb8, 0x56, 0xd7, 0x6a, 0xe1, 0xb9, 0xbe, 0xf7, 0x43,
	0x70, 0x33, 0x29, 0xaa, 0x42, 0xb9, 0x83, 0xf1, 0x05, 0xae, 0xdf, 0x43, 0x2e, 0x94, 0x5e, 0x7e,
	0x79, 0x76, 0x51, 0x77, 0x94, 0xf0, 0xb4, 0x73, 0xd2, 0x3f, 0xaf, 0x17, 0xbc, 0x17, 0x70, 0x70,
	0x42, 0xc6, 0x11, 0xb5, 0xd5, 0x69, 0x5c, 0xdc, 0xa6, 0x9c, 0xbd, 0xdf, 0x39, 0x80, 0xac, 0xf0,
	0x22, 0x95, 0x49, 0x2a, 0x0d, 0xd6, 0x2f, 0xa1, 0x62, 0x32, 0xaa, 0xa1, 0xf6, 0x8e, 0xbe, 0x9f,
	0x83, 0x5a, 0x37, 0x68, 0x75, 0x0d, 0x57, 0xad, 0x15, 0x7a, 0x0f, 0x2a, 0x4c, 0x7f, 0xb5, 0xd9,
	0xb1, 0x37, 0xaf, 0x09, 0x15, 0xa3, 0x89, 0x76, 0xa0, 0x78, 0xd1, 0xef, 0xd5, 0xef, 0xa9, 0x43,
	0x07, 0xe3, 0xba, 0xe3, 0xfd, 0xc5, 0x81, 0xfd, 0x0e, 0x0d, 0x73, 0x31, 0x3d, 0x86, 0x1a, 0x27,
	0x32, 0xe5, 0x74, 0x10, 0xb0, 0xd0, 0x3c, 0x6b, 0x59, 0xf5, 0x61, 0x25, 0x6a, 0xb3, 0x70, 0xad,
	0xc3, 0x14, 0xb6, 0xee, 0x30, 0xc5, 0xbb, 0x77, 0x98, 0xbf, 0x3a, 0x80, 0xce, 0x23, 0x69, 0xd8,
	0xdc, 0xf3, 0xc5, 0x1b, 0xe3, 0xeb, 0x7b, 0x50, 0x31, 0xf5, 0x6e, 0x49, 0x62, 0x6f, 0x2a, 0x97,
	0x9c, 0x88, 0x34, 0x36, 0xb9, 0x58, 0xcd, 0xe5, 0x3a, 0x50, 0x0b, 0x6b, 0x6d, 0x6c, 0xad, 0x36,
	0x8d, 0x1a, 0xf5, 0x9b, 0x9c, 0xf8, 0x82, 0x51, 0x5d, 0xa2, 0x55, 0x6c, 0x6f, 0xde, 0x87, 0x50,
	0x31, 0x28, 0xe8, 0x3e, 0x54, 0xbb, 0xfd, 0x76, 0xbb, 0xd3, 0x39, 0xed, 0x9c, 0xd6, 0xef, 0x21,
	0x80, 0xca, 0xd9, 0xf3, 0x97, 0xaf, 0x3b, 0xa7, 0x75, 0xc7, 0x7b, 0x02, 0xe8, 0xab, 0x28, 0x49,
	0x48, 0xd8, 0x66, 0x54, 0x12, 0x2a, 0xe7, 0x4c, 0x0f, 0x7d, 0xe9, 0xeb, 0x20, 0x76, 0xb1, 0x3e,
	0x7b, 0xff, 0x29, 0x82, 0xfb, 0x8a, 0x0d, 0x8d, 0x42, 0x0b, 0x4a, 0x77, 0x9c, 0x65, 0x5a, 0x0f,
	0x1d, 0x41, 0x35, 0x66, 0xe3, 0x01, 0x51, 0xc6, 0xd7, 0x4e, 0x8d, 0xac, 0x2a, 0xb0, 0x1b, 0x67,
	0xe5, 0xf6, 0x25, 0xbc, 0x33, 0x54, 0x04, 0x1f, 0x58, 0x9e, 0x5a, 0x6b, 0xf3, 0x48, 0xf9, 0x9a,
	0x5a, 0x2b, 0x04, 0x7c, 0x30, 0x5c, 0xab, 0x8d, 0x5f, 0xc3, 0xbb, 0x19, 0x92, 0x61, 0xa2, 0x05,
	0x34, 0x73, 0xe5, 0xf1, 0x2d, 0xec, 0xc6, 0x28, 0x58, 0x2f, 0x91, 0x17, 0x70, 0xa0, 0x66, 0x70,
	0xde, 0xc1, 0xb2, 0xc6, 0xfb, 0x20, 0x87, 0xb7, 0xc2, 0x69, 0xbc, 0x4f, 0x56, 0x48, 0xfe, 0x05,
	0x1c, 0x18, 0xaa, 0x0c, 0xa4, 0x2f, 0xde, 0x58, 0xa4, 0xca, 0x35, 0x9e, 0xad, 0x73, 0x05, 0xef,
	0x0f, 0x57, 0x58, 0x78, 0x06, 0x7b, 0xdf, 0xe8, 0x47, 0x1d, 0x04, 0xe6, 0x55, 0x1b, 0x3b, 0xd7,
	0x20, 0xad, 0xbf, 0x3b, 0xbe, 0xff, 0xcd, 0xb2, 0xcc, 0xfb, 0x83, 0x03, 0xbb, 0x7a, 0x3e, 0x5e,
	0x24, 0x8a, 0xfe, 0x42, 0xd1, 0x30, 0x89, 0x7d, 0x39, 0x62, 0x7c, 0x6a, 0x09, 0x3e, 0xbf, 0xab,
	0x4d, 0x45, 0xfa, 0x7c, 0x4c, 0xa4, 0x19, 0x6e, 0x55, 0x9c, 0x5d, 0xd1, 0xb9, 0x9a, 0x26, 0xd9,
	0x10, 0x18, 0x98, 0xcd, 0xa1, 0x78, 0x4d, 0x92, 0x56, 0xf6, 0x2f, 0x35, 0x6b, 0x72, 0x02, 0xef,
	0xbb, 0x00, 0x3d, 0x8d, 0xf9, 0x3a, 0x12, 0xba, 0xd6, 0xcc, 0x2f, 0xd8, 0xe5, 0xcf, 0xde, 0x94,
	0x96, 0xc9, 0x50, 0xa6, 0x35, 0xaf, 0xc8, 0xe2, 0xa2, 0x22, 0xbd, 0x7f, 0x39, 0x00, 0x38, 0xa5,
	0x77, 0x89, 0xec, 0x3a, 0xff, 0x0b, 0x5b, 0xf8, 0x8f, 0x9e, 0xc1, 0x6e, 0x48, 0x12, 0x42, 0x43,
	0x42, 0x83, 0x88, 0x08, 0x9b, 0x84, 0xfc, 0x3e, 0xb2, 0x08, 0x10, 0xe7, 0x94, 0x97, 0x5b, 0x7b,
	0xe9, 0xce, 0xad, 0xfd, 0xdf, 0x0e, 0xec, 0xb5, 0x63, 0x36, 0x1c, 0x12, 0xfe, 0x7f, 0x8d, 0xf4,
	0x78, 0xfe, 0x36, 0x66, 0x04, 0x7a, 0xf9, 0xea, 0xca, 0x79, 0x64, 0x43, 0xce, 0xde, 0x4f, 0x4d,
	0xf9, 0x11, 0xe3, 0x81, 0x59, 0xf8, 0x5c, 0x6c, 0x2e, 0xde, 0x21, 0x54, 0x8c, 0x9e, 0x6a, 0x5f,
	0xdd, 0x8b, 0x3e, 0x6e, 0x77, 0x4c, 0x2b, 0xbb, 0xe8, 0xf7, 0x2e, 0xfb, 0xbd, 0xba, 0xe3, 0x7d,
	0x07, 0x6a, 0x97, 0x11, 0x1d, 0x67, 0x71, 0x22, 0x28, 0x25, 0x6a, 0x6d, 0xb6, 0xd3, 0x5a, 0x9d,
	0xbd, 0x43, 0x00, 0xa5, 0x62, 0xdb, 0xa2, 0xd2, 0x60, 0x4b, 0x1a, 0x8c, 0x8e, 0xbd, 0x19, 0xd4,
	0xcf, 0xd4, 0xf0, 0x3f, 0x8b, 0x62, 0x92, 0x21, 0x7d, 0x08, 0xf7, 0x39, 0x89, 0x7d, 0x19, 0xcd,
	0xc8, 0x20, 0xf1, 0x65, 0xd6, 0xdb, 0x77, 0x33, 0xe1, 0xa5, 0x2f, 0x27, 0x4a, 0x69, 0x14, 0xc5,
	0x44, 0x6d, 0x1b, 0x83, 0x71, 0xcc, 0x86, 0x76, 0xe8, 0xed, 0x66, 0xc2, 0xf3, 0x98, 0x0d, 0xf5,
	0x36, 0x4f, 0x82, 0x94, 0x0b, 0x53, 0x00, 0x6a, 0x9b, 0x37, 0x57, 0x2f, 0x84, 0x77, 0x0c, 0x69,
	0xcd, 0x06, 0x94, 0xfd, 0xf4, 0x63, 0xa8, 0xd9, 0xb6, 0x20, 0x12, 0x12, 0xd8, 0x1f, 0x06, 0x23,
	0xea, 0x26, 0x24, 0x40, 0x3f, 0x02, 0x14, 0xd1, 0x20, 0x4e, 0x43, 0x32, 0x18, 0x47, 0x72, 0x60,
	0x57, 0x31, 0xf3, 0xa7, 0x42, 0xdd, 0x7e, 0x39, 0x8f, 0xa4, 0x41, 0x3d, 0xfa, 0x5b, 0x11, 0x0e,
	0x2e, 0xed, 0x63, 0xeb, 0xc2, 0x7e, 0xa1, 0x76, 0x98, 0x67, 0x50, 0xd6, 0x17, 0xf4, 0x70, 0x7d,
	0x33, 0xb6, 0x8e, 0x34, 0xf3, 0xdd, 0x3a, 0x9b, 0x03, 0x3f, 0x76, 0xd0, 0xcf, 0xa1, 0x88, 0x53,
	0x8a, 0x1e, 0xac, 0xfe, 0x0d, 0x70, 0xab, 0xe1, 0xe7, 0xb0, 0x63, 0x79, 0x80, 0xde, 0xdf, 0xc0,
	0x8e, 0x9b, 0x01, 0x9e, 0x41, 0xb9, 0x1d, 0x13, 0x9f, 0x6e, 0xe5, 0xf6, 0x67, 0xb0, 0x73, 0xc9,
	0x49, 0xe2, 0x73, 0xb2, 0x95, 0xf9, 0x73, 0xa8, 0xa9, 0x12, 0xed, 0xd9, 0x0e, 0xb7, 0x01, 0xe2,
	0xa6, 0xea, 0x46, 0x6d, 0xa8, 0xce, 0x99, 0x86, 0xbe, 0x9d, 0xd3, 0x5a, 0x65, 0xe0, 0x8d, 0x7e,
	0x1c, 0xfd, 0xa3, 0x0c, 0x7b, 0x8b, 0x62, 0xd4, 0xaf, 0xd9, 0x85, 0xfd, 0x73, 0x22, 0x97, 0xc9,
	0x84, 0x0e, 0xf3, 0xee, 0xad, 0xf3, 0xac, 0xf9, 0x68, 0xf3, 0xd6, 0x8e, 0x5e, 0xc1, 0x7e, 0x77,
	0x05, 0xf4, 0x16, 0x93, 0x9b, 0x73, 0x77, 0x0a, 0xf5, 0xcb, 0x34, 0x8e, 0xcf, 0x38, 0x9b, 0xce,
	0x77, 0xf6, 0x07, 0xd7, 0x78, 0xa8, 0xb2, 0x74, 0x33, 0xca, 0x09, 0xec, 0x5d, 0xa6, 0x62, 0xd2,
	0x63, 0x6f, 0x81, 0xf1, 0xb9, 0xda, 0x44, 0x7d, 0x99, 0x0a, 0xb4, 0xb1, 0xbd, 0x6d, 0x72, 0xa2,
	0xda, 0xbd, 0xa2, 0xc1, 0x6b, 0x16, 0xf8, 0xf1, 0xb6, 0x18, 0x6d, 0x00, 0x85, 0x81, 0xc9, 0x94,
	0x49, 0xb2, 0x2d, 0xc8, 0x2b, 0x38, 0xb0, 0x74, 0x3e, 0x63, 0x1c, 0x93, 0x80, 0x44, 0xb3, 0xad,
	0xb1, 0x3a, 0xb0, 0x8b, 0xc9, 0xd0, 0x17, 0xa4, 0x9f, 0x84, 0xfe, 0xf6, 0x2e, 0xfd, 0x4f, 0xf8,
	0xfd, 0xf7, 0x02, 0xd4, 0xba, 0x84, 0xcf, 0xa2, 0x80, 0x68, 0x72, 0x3f, 0x85, 0x92, 0x6a, 0xe0,
	0xa8, 0x91, 0x33, 0x58, 0x6a, 0xfb, 0x2b, 0xf5, 0xb6, 0xd4, 0xed, 0x4f, 0xc0, 0x55, 0x6c, 0xd0,
	0xff, 0x10, 0xd8, 0x1c, 0x52, 0xe3, 0x86, 0x7f, 0x10, 0x08, 0xf4, 0x19, 0xb8, 0x5f, 0x44, 0x71,
	0xac, 0xcf, 0x37, 0x6a, 0x6d, 0xea, 0x1a, 0x6e, 0x77, 0x92, 0xca, 0x90, 0x7d, 0x4d, 0xdf, 0x86,
	0x2d, 0x24, 0x1e, 0xbd, 0xd5, 0xd3, 0x0c, 0x2b, 0x7a, 0x4f, 0xff, 0xf4, 0xbf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xe8, 0x53, 0x3b, 0x70, 0xa8, 0x13, 0x00, 0x00,
}
