// Code generated by protoc-gen-go.
// source: stonesthrow/st.proto
// DO NOT EDIT!

/*
Package stonesthrow is a generated protocol buffer package.

It is generated from these files:
	stonesthrow/st.proto

It has these top-level messages:
	ShellCommand
	ShellTask
	RepositoryState
	RunState
	BuilderJob
	BuilderJobs
	GitBranchInfo
	LogEvent
	BeginCommandEvent
	CommandOutputEvent
	EndCommandEvent
	GitBranchTaskEvent
	JobEvent
	BuildOptions
	RunOptions
	TargetList
*/
package stonesthrow

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LogEvent_Severity int32

const (
	LogEvent_ERROR LogEvent_Severity = 0
	LogEvent_INFO  LogEvent_Severity = 1
	LogEvent_DEBUG LogEvent_Severity = 2
)

var LogEvent_Severity_name = map[int32]string{
	0: "ERROR",
	1: "INFO",
	2: "DEBUG",
}
var LogEvent_Severity_value = map[string]int32{
	"ERROR": 0,
	"INFO":  1,
	"DEBUG": 2,
}

func (x LogEvent_Severity) String() string {
	return proto.EnumName(LogEvent_Severity_name, int32(x))
}
func (LogEvent_Severity) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }

type CommandOutputEvent_Stream int32

const (
	CommandOutputEvent_OUT CommandOutputEvent_Stream = 0
	CommandOutputEvent_ERR CommandOutputEvent_Stream = 1
)

var CommandOutputEvent_Stream_name = map[int32]string{
	0: "OUT",
	1: "ERR",
}
var CommandOutputEvent_Stream_value = map[string]int32{
	"OUT": 0,
	"ERR": 1,
}

func (x CommandOutputEvent_Stream) String() string {
	return proto.EnumName(CommandOutputEvent_Stream_name, int32(x))
}
func (CommandOutputEvent_Stream) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{9, 0} }

type GitBranchTaskEvent_Result int32

const (
	GitBranchTaskEvent_SUCCEEDED GitBranchTaskEvent_Result = 0
	GitBranchTaskEvent_FAILED    GitBranchTaskEvent_Result = 1
)

var GitBranchTaskEvent_Result_name = map[int32]string{
	0: "SUCCEEDED",
	1: "FAILED",
}
var GitBranchTaskEvent_Result_value = map[string]int32{
	"SUCCEEDED": 0,
	"FAILED":    1,
}

func (x GitBranchTaskEvent_Result) String() string {
	return proto.EnumName(GitBranchTaskEvent_Result_name, int32(x))
}
func (GitBranchTaskEvent_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{11, 0}
}

type ShellCommand struct {
	Command   []string `protobuf:"bytes,1,rep,name=command" json:"command,omitempty"`
	Directory string   `protobuf:"bytes,2,opt,name=directory" json:"directory,omitempty"`
	Host      string   `protobuf:"bytes,3,opt,name=host" json:"host,omitempty"`
}

func (m *ShellCommand) Reset()                    { *m = ShellCommand{} }
func (m *ShellCommand) String() string            { return proto.CompactTextString(m) }
func (*ShellCommand) ProtoMessage()               {}
func (*ShellCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ShellCommand) GetCommand() []string {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *ShellCommand) GetDirectory() string {
	if m != nil {
		return m.Directory
	}
	return ""
}

func (m *ShellCommand) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

type ShellTask struct {
	Command      *ShellCommand `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
	State        *RunState     `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	SystemTimeNs int64         `protobuf:"varint,3,opt,name=system_time_ns,json=systemTimeNs" json:"system_time_ns,omitempty"`
	UserTimeNs   int64         `protobuf:"varint,4,opt,name=user_time_ns,json=userTimeNs" json:"user_time_ns,omitempty"`
}

func (m *ShellTask) Reset()                    { *m = ShellTask{} }
func (m *ShellTask) String() string            { return proto.CompactTextString(m) }
func (*ShellTask) ProtoMessage()               {}
func (*ShellTask) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ShellTask) GetCommand() *ShellCommand {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *ShellTask) GetState() *RunState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *ShellTask) GetSystemTimeNs() int64 {
	if m != nil {
		return m.SystemTimeNs
	}
	return 0
}

func (m *ShellTask) GetUserTimeNs() int64 {
	if m != nil {
		return m.UserTimeNs
	}
	return 0
}

type RepositoryState struct {
	Repository string `protobuf:"bytes,2,opt,name=repository" json:"repository,omitempty"`
	Revision   string `protobuf:"bytes,3,opt,name=revision" json:"revision,omitempty"`
}

func (m *RepositoryState) Reset()                    { *m = RepositoryState{} }
func (m *RepositoryState) String() string            { return proto.CompactTextString(m) }
func (*RepositoryState) ProtoMessage()               {}
func (*RepositoryState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RepositoryState) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *RepositoryState) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

type RunState struct {
	StartTime int64 `protobuf:"varint,1,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	Running   bool  `protobuf:"varint,2,opt,name=running" json:"running,omitempty"`
	EndTime   int64 `protobuf:"varint,3,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
}

func (m *RunState) Reset()                    { *m = RunState{} }
func (m *RunState) String() string            { return proto.CompactTextString(m) }
func (*RunState) ProtoMessage()               {}
func (*RunState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RunState) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *RunState) GetRunning() bool {
	if m != nil {
		return m.Running
	}
	return false
}

func (m *RunState) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

type BuilderJob struct {
	Id              int32            `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Request         string           `protobuf:"bytes,2,opt,name=request" json:"request,omitempty"`
	RepositoryState *RepositoryState `protobuf:"bytes,3,opt,name=repository_state,json=repositoryState" json:"repository_state,omitempty"`
	RunState        *RunState        `protobuf:"bytes,4,opt,name=run_state,json=runState" json:"run_state,omitempty"`
	ShellTasks      []*ShellTask     `protobuf:"bytes,5,rep,name=shell_tasks,json=shellTasks" json:"shell_tasks,omitempty"`
}

func (m *BuilderJob) Reset()                    { *m = BuilderJob{} }
func (m *BuilderJob) String() string            { return proto.CompactTextString(m) }
func (*BuilderJob) ProtoMessage()               {}
func (*BuilderJob) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BuilderJob) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BuilderJob) GetRequest() string {
	if m != nil {
		return m.Request
	}
	return ""
}

func (m *BuilderJob) GetRepositoryState() *RepositoryState {
	if m != nil {
		return m.RepositoryState
	}
	return nil
}

func (m *BuilderJob) GetRunState() *RunState {
	if m != nil {
		return m.RunState
	}
	return nil
}

func (m *BuilderJob) GetShellTasks() []*ShellTask {
	if m != nil {
		return m.ShellTasks
	}
	return nil
}

type BuilderJobs struct {
	Jobs []*BuilderJob `protobuf:"bytes,1,rep,name=jobs" json:"jobs,omitempty"`
}

func (m *BuilderJobs) Reset()                    { *m = BuilderJobs{} }
func (m *BuilderJobs) String() string            { return proto.CompactTextString(m) }
func (*BuilderJobs) ProtoMessage()               {}
func (*BuilderJobs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *BuilderJobs) GetJobs() []*BuilderJob {
	if m != nil {
		return m.Jobs
	}
	return nil
}

type GitBranchInfo struct {
	Branches []*GitBranchInfo_GitBranch `protobuf:"bytes,1,rep,name=branches" json:"branches,omitempty"`
	Upstream []string                   `protobuf:"bytes,2,rep,name=upstream" json:"upstream,omitempty"`
}

func (m *GitBranchInfo) Reset()                    { *m = GitBranchInfo{} }
func (m *GitBranchInfo) String() string            { return proto.CompactTextString(m) }
func (*GitBranchInfo) ProtoMessage()               {}
func (*GitBranchInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GitBranchInfo) GetBranches() []*GitBranchInfo_GitBranch {
	if m != nil {
		return m.Branches
	}
	return nil
}

func (m *GitBranchInfo) GetUpstream() []string {
	if m != nil {
		return m.Upstream
	}
	return nil
}

type GitBranchInfo_GitBranch struct {
	Name            string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Revision        string            `protobuf:"bytes,2,opt,name=revision" json:"revision,omitempty"`
	RevisionsAhead  int32             `protobuf:"varint,3,opt,name=revisions_ahead,json=revisionsAhead" json:"revisions_ahead,omitempty"`
	RevisionsBehind int32             `protobuf:"varint,4,opt,name=revisions_behind,json=revisionsBehind" json:"revisions_behind,omitempty"`
	Config          map[string]string `protobuf:"bytes,5,rep,name=config" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *GitBranchInfo_GitBranch) Reset()                    { *m = GitBranchInfo_GitBranch{} }
func (m *GitBranchInfo_GitBranch) String() string            { return proto.CompactTextString(m) }
func (*GitBranchInfo_GitBranch) ProtoMessage()               {}
func (*GitBranchInfo_GitBranch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

func (m *GitBranchInfo_GitBranch) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GitBranchInfo_GitBranch) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

func (m *GitBranchInfo_GitBranch) GetRevisionsAhead() int32 {
	if m != nil {
		return m.RevisionsAhead
	}
	return 0
}

func (m *GitBranchInfo_GitBranch) GetRevisionsBehind() int32 {
	if m != nil {
		return m.RevisionsBehind
	}
	return 0
}

func (m *GitBranchInfo_GitBranch) GetConfig() map[string]string {
	if m != nil {
		return m.Config
	}
	return nil
}

type LogEvent struct {
	Host     string            `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	Msg      string            `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Severity LogEvent_Severity `protobuf:"varint,3,opt,name=severity,enum=stonesthrow.LogEvent_Severity" json:"severity,omitempty"`
}

func (m *LogEvent) Reset()                    { *m = LogEvent{} }
func (m *LogEvent) String() string            { return proto.CompactTextString(m) }
func (*LogEvent) ProtoMessage()               {}
func (*LogEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *LogEvent) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *LogEvent) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LogEvent) GetSeverity() LogEvent_Severity {
	if m != nil {
		return m.Severity
	}
	return LogEvent_ERROR
}

type BeginCommandEvent struct {
	Command *ShellCommand `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
}

func (m *BeginCommandEvent) Reset()                    { *m = BeginCommandEvent{} }
func (m *BeginCommandEvent) String() string            { return proto.CompactTextString(m) }
func (*BeginCommandEvent) ProtoMessage()               {}
func (*BeginCommandEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *BeginCommandEvent) GetCommand() *ShellCommand {
	if m != nil {
		return m.Command
	}
	return nil
}

type CommandOutputEvent struct {
	Stream CommandOutputEvent_Stream `protobuf:"varint,1,opt,name=stream,enum=stonesthrow.CommandOutputEvent_Stream" json:"stream,omitempty"`
	Output string                    `protobuf:"bytes,2,opt,name=output" json:"output,omitempty"`
}

func (m *CommandOutputEvent) Reset()                    { *m = CommandOutputEvent{} }
func (m *CommandOutputEvent) String() string            { return proto.CompactTextString(m) }
func (*CommandOutputEvent) ProtoMessage()               {}
func (*CommandOutputEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CommandOutputEvent) GetStream() CommandOutputEvent_Stream {
	if m != nil {
		return m.Stream
	}
	return CommandOutputEvent_OUT
}

func (m *CommandOutputEvent) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

type EndCommandEvent struct {
	ReturnCode   int32 `protobuf:"varint,1,opt,name=return_code,json=returnCode" json:"return_code,omitempty"`
	SystemTimeNs int64 `protobuf:"varint,2,opt,name=system_time_ns,json=systemTimeNs" json:"system_time_ns,omitempty"`
	UserTimeNs   int64 `protobuf:"varint,3,opt,name=user_time_ns,json=userTimeNs" json:"user_time_ns,omitempty"`
}

func (m *EndCommandEvent) Reset()                    { *m = EndCommandEvent{} }
func (m *EndCommandEvent) String() string            { return proto.CompactTextString(m) }
func (*EndCommandEvent) ProtoMessage()               {}
func (*EndCommandEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *EndCommandEvent) GetReturnCode() int32 {
	if m != nil {
		return m.ReturnCode
	}
	return 0
}

func (m *EndCommandEvent) GetSystemTimeNs() int64 {
	if m != nil {
		return m.SystemTimeNs
	}
	return 0
}

func (m *EndCommandEvent) GetUserTimeNs() int64 {
	if m != nil {
		return m.UserTimeNs
	}
	return 0
}

type GitBranchTaskEvent struct {
	Branch   string                    `protobuf:"bytes,1,opt,name=branch" json:"branch,omitempty"`
	Result   GitBranchTaskEvent_Result `protobuf:"varint,2,opt,name=result,enum=stonesthrow.GitBranchTaskEvent_Result" json:"result,omitempty"`
	Revision string                    `protobuf:"bytes,3,opt,name=revision" json:"revision,omitempty"`
	Reason   string                    `protobuf:"bytes,4,opt,name=reason" json:"reason,omitempty"`
}

func (m *GitBranchTaskEvent) Reset()                    { *m = GitBranchTaskEvent{} }
func (m *GitBranchTaskEvent) String() string            { return proto.CompactTextString(m) }
func (*GitBranchTaskEvent) ProtoMessage()               {}
func (*GitBranchTaskEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GitBranchTaskEvent) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *GitBranchTaskEvent) GetResult() GitBranchTaskEvent_Result {
	if m != nil {
		return m.Result
	}
	return GitBranchTaskEvent_SUCCEEDED
}

func (m *GitBranchTaskEvent) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

func (m *GitBranchTaskEvent) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type JobEvent struct {
	LogEvent           *LogEvent           `protobuf:"bytes,1,opt,name=log_event,json=logEvent" json:"log_event,omitempty"`
	BeginCommandEvent  *BeginCommandEvent  `protobuf:"bytes,2,opt,name=begin_command_event,json=beginCommandEvent" json:"begin_command_event,omitempty"`
	CommandOutputEvent *CommandOutputEvent `protobuf:"bytes,3,opt,name=command_output_event,json=commandOutputEvent" json:"command_output_event,omitempty"`
	EndCommandEvent    *EndCommandEvent    `protobuf:"bytes,4,opt,name=end_command_event,json=endCommandEvent" json:"end_command_event,omitempty"`
	BranchTaskEvent    *GitBranchTaskEvent `protobuf:"bytes,5,opt,name=branch_task_event,json=branchTaskEvent" json:"branch_task_event,omitempty"`
}

func (m *JobEvent) Reset()                    { *m = JobEvent{} }
func (m *JobEvent) String() string            { return proto.CompactTextString(m) }
func (*JobEvent) ProtoMessage()               {}
func (*JobEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *JobEvent) GetLogEvent() *LogEvent {
	if m != nil {
		return m.LogEvent
	}
	return nil
}

func (m *JobEvent) GetBeginCommandEvent() *BeginCommandEvent {
	if m != nil {
		return m.BeginCommandEvent
	}
	return nil
}

func (m *JobEvent) GetCommandOutputEvent() *CommandOutputEvent {
	if m != nil {
		return m.CommandOutputEvent
	}
	return nil
}

func (m *JobEvent) GetEndCommandEvent() *EndCommandEvent {
	if m != nil {
		return m.EndCommandEvent
	}
	return nil
}

func (m *JobEvent) GetBranchTaskEvent() *GitBranchTaskEvent {
	if m != nil {
		return m.BranchTaskEvent
	}
	return nil
}

type BuildOptions struct {
	Targets         []string         `protobuf:"bytes,1,rep,name=targets" json:"targets,omitempty"`
	RepositoryState *RepositoryState `protobuf:"bytes,2,opt,name=repository_state,json=repositoryState" json:"repository_state,omitempty"`
}

func (m *BuildOptions) Reset()                    { *m = BuildOptions{} }
func (m *BuildOptions) String() string            { return proto.CompactTextString(m) }
func (*BuildOptions) ProtoMessage()               {}
func (*BuildOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *BuildOptions) GetTargets() []string {
	if m != nil {
		return m.Targets
	}
	return nil
}

func (m *BuildOptions) GetRepositoryState() *RepositoryState {
	if m != nil {
		return m.RepositoryState
	}
	return nil
}

type RunOptions struct {
	Command         *ShellCommand    `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
	RepositoryState *RepositoryState `protobuf:"bytes,2,opt,name=repository_state,json=repositoryState" json:"repository_state,omitempty"`
}

func (m *RunOptions) Reset()                    { *m = RunOptions{} }
func (m *RunOptions) String() string            { return proto.CompactTextString(m) }
func (*RunOptions) ProtoMessage()               {}
func (*RunOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *RunOptions) GetCommand() *ShellCommand {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *RunOptions) GetRepositoryState() *RepositoryState {
	if m != nil {
		return m.RepositoryState
	}
	return nil
}

type TargetList struct {
	Target []string `protobuf:"bytes,1,rep,name=target" json:"target,omitempty"`
}

func (m *TargetList) Reset()                    { *m = TargetList{} }
func (m *TargetList) String() string            { return proto.CompactTextString(m) }
func (*TargetList) ProtoMessage()               {}
func (*TargetList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *TargetList) GetTarget() []string {
	if m != nil {
		return m.Target
	}
	return nil
}

func init() {
	proto.RegisterType((*ShellCommand)(nil), "stonesthrow.ShellCommand")
	proto.RegisterType((*ShellTask)(nil), "stonesthrow.ShellTask")
	proto.RegisterType((*RepositoryState)(nil), "stonesthrow.RepositoryState")
	proto.RegisterType((*RunState)(nil), "stonesthrow.RunState")
	proto.RegisterType((*BuilderJob)(nil), "stonesthrow.BuilderJob")
	proto.RegisterType((*BuilderJobs)(nil), "stonesthrow.BuilderJobs")
	proto.RegisterType((*GitBranchInfo)(nil), "stonesthrow.GitBranchInfo")
	proto.RegisterType((*GitBranchInfo_GitBranch)(nil), "stonesthrow.GitBranchInfo.GitBranch")
	proto.RegisterType((*LogEvent)(nil), "stonesthrow.LogEvent")
	proto.RegisterType((*BeginCommandEvent)(nil), "stonesthrow.BeginCommandEvent")
	proto.RegisterType((*CommandOutputEvent)(nil), "stonesthrow.CommandOutputEvent")
	proto.RegisterType((*EndCommandEvent)(nil), "stonesthrow.EndCommandEvent")
	proto.RegisterType((*GitBranchTaskEvent)(nil), "stonesthrow.GitBranchTaskEvent")
	proto.RegisterType((*JobEvent)(nil), "stonesthrow.JobEvent")
	proto.RegisterType((*BuildOptions)(nil), "stonesthrow.BuildOptions")
	proto.RegisterType((*RunOptions)(nil), "stonesthrow.RunOptions")
	proto.RegisterType((*TargetList)(nil), "stonesthrow.TargetList")
	proto.RegisterEnum("stonesthrow.LogEvent_Severity", LogEvent_Severity_name, LogEvent_Severity_value)
	proto.RegisterEnum("stonesthrow.CommandOutputEvent_Stream", CommandOutputEvent_Stream_name, CommandOutputEvent_Stream_value)
	proto.RegisterEnum("stonesthrow.GitBranchTaskEvent_Result", GitBranchTaskEvent_Result_name, GitBranchTaskEvent_Result_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PlatformBuildHost service

type PlatformBuildHostClient interface {
	ListJobs(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (*BuilderJobs, error)
	KillJobs(ctx context.Context, in *BuilderJobs, opts ...grpc.CallOption) (PlatformBuildHost_KillJobsClient, error)
	Build(ctx context.Context, in *BuildOptions, opts ...grpc.CallOption) (PlatformBuildHost_BuildClient, error)
	Run(ctx context.Context, in *RunOptions, opts ...grpc.CallOption) (PlatformBuildHost_RunClient, error)
	Clobber(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (PlatformBuildHost_ClobberClient, error)
	Prepare(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (PlatformBuildHost_PrepareClient, error)
	ListTargets(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (*TargetList, error)
}

type platformBuildHostClient struct {
	cc *grpc.ClientConn
}

func NewPlatformBuildHostClient(cc *grpc.ClientConn) PlatformBuildHostClient {
	return &platformBuildHostClient{cc}
}

func (c *platformBuildHostClient) ListJobs(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (*BuilderJobs, error) {
	out := new(BuilderJobs)
	err := grpc.Invoke(ctx, "/stonesthrow.PlatformBuildHost/ListJobs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformBuildHostClient) KillJobs(ctx context.Context, in *BuilderJobs, opts ...grpc.CallOption) (PlatformBuildHost_KillJobsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PlatformBuildHost_serviceDesc.Streams[0], c.cc, "/stonesthrow.PlatformBuildHost/KillJobs", opts...)
	if err != nil {
		return nil, err
	}
	x := &platformBuildHostKillJobsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PlatformBuildHost_KillJobsClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type platformBuildHostKillJobsClient struct {
	grpc.ClientStream
}

func (x *platformBuildHostKillJobsClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *platformBuildHostClient) Build(ctx context.Context, in *BuildOptions, opts ...grpc.CallOption) (PlatformBuildHost_BuildClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PlatformBuildHost_serviceDesc.Streams[1], c.cc, "/stonesthrow.PlatformBuildHost/Build", opts...)
	if err != nil {
		return nil, err
	}
	x := &platformBuildHostBuildClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PlatformBuildHost_BuildClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type platformBuildHostBuildClient struct {
	grpc.ClientStream
}

func (x *platformBuildHostBuildClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *platformBuildHostClient) Run(ctx context.Context, in *RunOptions, opts ...grpc.CallOption) (PlatformBuildHost_RunClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PlatformBuildHost_serviceDesc.Streams[2], c.cc, "/stonesthrow.PlatformBuildHost/Run", opts...)
	if err != nil {
		return nil, err
	}
	x := &platformBuildHostRunClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PlatformBuildHost_RunClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type platformBuildHostRunClient struct {
	grpc.ClientStream
}

func (x *platformBuildHostRunClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *platformBuildHostClient) Clobber(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (PlatformBuildHost_ClobberClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PlatformBuildHost_serviceDesc.Streams[3], c.cc, "/stonesthrow.PlatformBuildHost/Clobber", opts...)
	if err != nil {
		return nil, err
	}
	x := &platformBuildHostClobberClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PlatformBuildHost_ClobberClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type platformBuildHostClobberClient struct {
	grpc.ClientStream
}

func (x *platformBuildHostClobberClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *platformBuildHostClient) Prepare(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (PlatformBuildHost_PrepareClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PlatformBuildHost_serviceDesc.Streams[4], c.cc, "/stonesthrow.PlatformBuildHost/Prepare", opts...)
	if err != nil {
		return nil, err
	}
	x := &platformBuildHostPrepareClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PlatformBuildHost_PrepareClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type platformBuildHostPrepareClient struct {
	grpc.ClientStream
}

func (x *platformBuildHostPrepareClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *platformBuildHostClient) ListTargets(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (*TargetList, error) {
	out := new(TargetList)
	err := grpc.Invoke(ctx, "/stonesthrow.PlatformBuildHost/ListTargets", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PlatformBuildHost service

type PlatformBuildHostServer interface {
	ListJobs(context.Context, *RepositoryState) (*BuilderJobs, error)
	KillJobs(*BuilderJobs, PlatformBuildHost_KillJobsServer) error
	Build(*BuildOptions, PlatformBuildHost_BuildServer) error
	Run(*RunOptions, PlatformBuildHost_RunServer) error
	Clobber(*RepositoryState, PlatformBuildHost_ClobberServer) error
	Prepare(*RepositoryState, PlatformBuildHost_PrepareServer) error
	ListTargets(context.Context, *RepositoryState) (*TargetList, error)
}

func RegisterPlatformBuildHostServer(s *grpc.Server, srv PlatformBuildHostServer) {
	s.RegisterService(&_PlatformBuildHost_serviceDesc, srv)
}

func _PlatformBuildHost_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepositoryState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformBuildHostServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stonesthrow.PlatformBuildHost/ListJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformBuildHostServer).ListJobs(ctx, req.(*RepositoryState))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformBuildHost_KillJobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BuilderJobs)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlatformBuildHostServer).KillJobs(m, &platformBuildHostKillJobsServer{stream})
}

type PlatformBuildHost_KillJobsServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type platformBuildHostKillJobsServer struct {
	grpc.ServerStream
}

func (x *platformBuildHostKillJobsServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _PlatformBuildHost_Build_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BuildOptions)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlatformBuildHostServer).Build(m, &platformBuildHostBuildServer{stream})
}

type PlatformBuildHost_BuildServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type platformBuildHostBuildServer struct {
	grpc.ServerStream
}

func (x *platformBuildHostBuildServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _PlatformBuildHost_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunOptions)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlatformBuildHostServer).Run(m, &platformBuildHostRunServer{stream})
}

type PlatformBuildHost_RunServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type platformBuildHostRunServer struct {
	grpc.ServerStream
}

func (x *platformBuildHostRunServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _PlatformBuildHost_Clobber_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RepositoryState)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlatformBuildHostServer).Clobber(m, &platformBuildHostClobberServer{stream})
}

type PlatformBuildHost_ClobberServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type platformBuildHostClobberServer struct {
	grpc.ServerStream
}

func (x *platformBuildHostClobberServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _PlatformBuildHost_Prepare_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RepositoryState)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlatformBuildHostServer).Prepare(m, &platformBuildHostPrepareServer{stream})
}

type PlatformBuildHost_PrepareServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type platformBuildHostPrepareServer struct {
	grpc.ServerStream
}

func (x *platformBuildHostPrepareServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _PlatformBuildHost_ListTargets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepositoryState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformBuildHostServer).ListTargets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stonesthrow.PlatformBuildHost/ListTargets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformBuildHostServer).ListTargets(ctx, req.(*RepositoryState))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlatformBuildHost_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stonesthrow.PlatformBuildHost",
	HandlerType: (*PlatformBuildHostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListJobs",
			Handler:    _PlatformBuildHost_ListJobs_Handler,
		},
		{
			MethodName: "ListTargets",
			Handler:    _PlatformBuildHost_ListTargets_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "KillJobs",
			Handler:       _PlatformBuildHost_KillJobs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Build",
			Handler:       _PlatformBuildHost_Build_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Run",
			Handler:       _PlatformBuildHost_Run_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Clobber",
			Handler:       _PlatformBuildHost_Clobber_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Prepare",
			Handler:       _PlatformBuildHost_Prepare_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "stonesthrow/st.proto",
}

// Client API for RepositoryHost service

type RepositoryHostClient interface {
	GetBranchConfig(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (*GitBranchInfo, error)
	SetBranchConfig(ctx context.Context, in *GitBranchInfo, opts ...grpc.CallOption) (RepositoryHost_SetBranchConfigClient, error)
	PullFromUpstream(ctx context.Context, in *GitBranchInfo, opts ...grpc.CallOption) (RepositoryHost_PullFromUpstreamClient, error)
	PushToUpstream(ctx context.Context, in *GitBranchInfo, opts ...grpc.CallOption) (RepositoryHost_PushToUpstreamClient, error)
	Status(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (RepositoryHost_StatusClient, error)
	SyncLocal(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (RepositoryHost_SyncLocalClient, error)
	Sync(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (RepositoryHost_SyncClient, error)
	PrepareForReceive(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (RepositoryHost_PrepareForReceiveClient, error)
}

type repositoryHostClient struct {
	cc *grpc.ClientConn
}

func NewRepositoryHostClient(cc *grpc.ClientConn) RepositoryHostClient {
	return &repositoryHostClient{cc}
}

func (c *repositoryHostClient) GetBranchConfig(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (*GitBranchInfo, error) {
	out := new(GitBranchInfo)
	err := grpc.Invoke(ctx, "/stonesthrow.RepositoryHost/GetBranchConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryHostClient) SetBranchConfig(ctx context.Context, in *GitBranchInfo, opts ...grpc.CallOption) (RepositoryHost_SetBranchConfigClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RepositoryHost_serviceDesc.Streams[0], c.cc, "/stonesthrow.RepositoryHost/SetBranchConfig", opts...)
	if err != nil {
		return nil, err
	}
	x := &repositoryHostSetBranchConfigClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RepositoryHost_SetBranchConfigClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type repositoryHostSetBranchConfigClient struct {
	grpc.ClientStream
}

func (x *repositoryHostSetBranchConfigClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *repositoryHostClient) PullFromUpstream(ctx context.Context, in *GitBranchInfo, opts ...grpc.CallOption) (RepositoryHost_PullFromUpstreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RepositoryHost_serviceDesc.Streams[1], c.cc, "/stonesthrow.RepositoryHost/PullFromUpstream", opts...)
	if err != nil {
		return nil, err
	}
	x := &repositoryHostPullFromUpstreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RepositoryHost_PullFromUpstreamClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type repositoryHostPullFromUpstreamClient struct {
	grpc.ClientStream
}

func (x *repositoryHostPullFromUpstreamClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *repositoryHostClient) PushToUpstream(ctx context.Context, in *GitBranchInfo, opts ...grpc.CallOption) (RepositoryHost_PushToUpstreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RepositoryHost_serviceDesc.Streams[2], c.cc, "/stonesthrow.RepositoryHost/PushToUpstream", opts...)
	if err != nil {
		return nil, err
	}
	x := &repositoryHostPushToUpstreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RepositoryHost_PushToUpstreamClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type repositoryHostPushToUpstreamClient struct {
	grpc.ClientStream
}

func (x *repositoryHostPushToUpstreamClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *repositoryHostClient) Status(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (RepositoryHost_StatusClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RepositoryHost_serviceDesc.Streams[3], c.cc, "/stonesthrow.RepositoryHost/Status", opts...)
	if err != nil {
		return nil, err
	}
	x := &repositoryHostStatusClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RepositoryHost_StatusClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type repositoryHostStatusClient struct {
	grpc.ClientStream
}

func (x *repositoryHostStatusClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *repositoryHostClient) SyncLocal(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (RepositoryHost_SyncLocalClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RepositoryHost_serviceDesc.Streams[4], c.cc, "/stonesthrow.RepositoryHost/SyncLocal", opts...)
	if err != nil {
		return nil, err
	}
	x := &repositoryHostSyncLocalClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RepositoryHost_SyncLocalClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type repositoryHostSyncLocalClient struct {
	grpc.ClientStream
}

func (x *repositoryHostSyncLocalClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *repositoryHostClient) Sync(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (RepositoryHost_SyncClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RepositoryHost_serviceDesc.Streams[5], c.cc, "/stonesthrow.RepositoryHost/Sync", opts...)
	if err != nil {
		return nil, err
	}
	x := &repositoryHostSyncClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RepositoryHost_SyncClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type repositoryHostSyncClient struct {
	grpc.ClientStream
}

func (x *repositoryHostSyncClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *repositoryHostClient) PrepareForReceive(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (RepositoryHost_PrepareForReceiveClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RepositoryHost_serviceDesc.Streams[6], c.cc, "/stonesthrow.RepositoryHost/PrepareForReceive", opts...)
	if err != nil {
		return nil, err
	}
	x := &repositoryHostPrepareForReceiveClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RepositoryHost_PrepareForReceiveClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type repositoryHostPrepareForReceiveClient struct {
	grpc.ClientStream
}

func (x *repositoryHostPrepareForReceiveClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for RepositoryHost service

type RepositoryHostServer interface {
	GetBranchConfig(context.Context, *RepositoryState) (*GitBranchInfo, error)
	SetBranchConfig(*GitBranchInfo, RepositoryHost_SetBranchConfigServer) error
	PullFromUpstream(*GitBranchInfo, RepositoryHost_PullFromUpstreamServer) error
	PushToUpstream(*GitBranchInfo, RepositoryHost_PushToUpstreamServer) error
	Status(*RepositoryState, RepositoryHost_StatusServer) error
	SyncLocal(*RepositoryState, RepositoryHost_SyncLocalServer) error
	Sync(*RepositoryState, RepositoryHost_SyncServer) error
	PrepareForReceive(*RepositoryState, RepositoryHost_PrepareForReceiveServer) error
}

func RegisterRepositoryHostServer(s *grpc.Server, srv RepositoryHostServer) {
	s.RegisterService(&_RepositoryHost_serviceDesc, srv)
}

func _RepositoryHost_GetBranchConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepositoryState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryHostServer).GetBranchConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stonesthrow.RepositoryHost/GetBranchConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryHostServer).GetBranchConfig(ctx, req.(*RepositoryState))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepositoryHost_SetBranchConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GitBranchInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RepositoryHostServer).SetBranchConfig(m, &repositoryHostSetBranchConfigServer{stream})
}

type RepositoryHost_SetBranchConfigServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type repositoryHostSetBranchConfigServer struct {
	grpc.ServerStream
}

func (x *repositoryHostSetBranchConfigServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _RepositoryHost_PullFromUpstream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GitBranchInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RepositoryHostServer).PullFromUpstream(m, &repositoryHostPullFromUpstreamServer{stream})
}

type RepositoryHost_PullFromUpstreamServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type repositoryHostPullFromUpstreamServer struct {
	grpc.ServerStream
}

func (x *repositoryHostPullFromUpstreamServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _RepositoryHost_PushToUpstream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GitBranchInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RepositoryHostServer).PushToUpstream(m, &repositoryHostPushToUpstreamServer{stream})
}

type RepositoryHost_PushToUpstreamServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type repositoryHostPushToUpstreamServer struct {
	grpc.ServerStream
}

func (x *repositoryHostPushToUpstreamServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _RepositoryHost_Status_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RepositoryState)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RepositoryHostServer).Status(m, &repositoryHostStatusServer{stream})
}

type RepositoryHost_StatusServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type repositoryHostStatusServer struct {
	grpc.ServerStream
}

func (x *repositoryHostStatusServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _RepositoryHost_SyncLocal_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RepositoryState)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RepositoryHostServer).SyncLocal(m, &repositoryHostSyncLocalServer{stream})
}

type RepositoryHost_SyncLocalServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type repositoryHostSyncLocalServer struct {
	grpc.ServerStream
}

func (x *repositoryHostSyncLocalServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _RepositoryHost_Sync_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RepositoryState)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RepositoryHostServer).Sync(m, &repositoryHostSyncServer{stream})
}

type RepositoryHost_SyncServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type repositoryHostSyncServer struct {
	grpc.ServerStream
}

func (x *repositoryHostSyncServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _RepositoryHost_PrepareForReceive_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RepositoryState)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RepositoryHostServer).PrepareForReceive(m, &repositoryHostPrepareForReceiveServer{stream})
}

type RepositoryHost_PrepareForReceiveServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type repositoryHostPrepareForReceiveServer struct {
	grpc.ServerStream
}

func (x *repositoryHostPrepareForReceiveServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

var _RepositoryHost_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stonesthrow.RepositoryHost",
	HandlerType: (*RepositoryHostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBranchConfig",
			Handler:    _RepositoryHost_GetBranchConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SetBranchConfig",
			Handler:       _RepositoryHost_SetBranchConfig_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PullFromUpstream",
			Handler:       _RepositoryHost_PullFromUpstream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PushToUpstream",
			Handler:       _RepositoryHost_PushToUpstream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Status",
			Handler:       _RepositoryHost_Status_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SyncLocal",
			Handler:       _RepositoryHost_SyncLocal_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Sync",
			Handler:       _RepositoryHost_Sync_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PrepareForReceive",
			Handler:       _RepositoryHost_PrepareForReceive_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "stonesthrow/st.proto",
}

// Client API for ServiceControl service

type ServiceControlClient interface {
	Shutdown(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (ServiceControl_ShutdownClient, error)
	SelfUpdate(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (ServiceControl_SelfUpdateClient, error)
}

type serviceControlClient struct {
	cc *grpc.ClientConn
}

func NewServiceControlClient(cc *grpc.ClientConn) ServiceControlClient {
	return &serviceControlClient{cc}
}

func (c *serviceControlClient) Shutdown(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (ServiceControl_ShutdownClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ServiceControl_serviceDesc.Streams[0], c.cc, "/stonesthrow.ServiceControl/Shutdown", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceControlShutdownClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ServiceControl_ShutdownClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type serviceControlShutdownClient struct {
	grpc.ClientStream
}

func (x *serviceControlShutdownClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serviceControlClient) SelfUpdate(ctx context.Context, in *RepositoryState, opts ...grpc.CallOption) (ServiceControl_SelfUpdateClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ServiceControl_serviceDesc.Streams[1], c.cc, "/stonesthrow.ServiceControl/SelfUpdate", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceControlSelfUpdateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ServiceControl_SelfUpdateClient interface {
	Recv() (*JobEvent, error)
	grpc.ClientStream
}

type serviceControlSelfUpdateClient struct {
	grpc.ClientStream
}

func (x *serviceControlSelfUpdateClient) Recv() (*JobEvent, error) {
	m := new(JobEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for ServiceControl service

type ServiceControlServer interface {
	Shutdown(*RepositoryState, ServiceControl_ShutdownServer) error
	SelfUpdate(*RepositoryState, ServiceControl_SelfUpdateServer) error
}

func RegisterServiceControlServer(s *grpc.Server, srv ServiceControlServer) {
	s.RegisterService(&_ServiceControl_serviceDesc, srv)
}

func _ServiceControl_Shutdown_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RepositoryState)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceControlServer).Shutdown(m, &serviceControlShutdownServer{stream})
}

type ServiceControl_ShutdownServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type serviceControlShutdownServer struct {
	grpc.ServerStream
}

func (x *serviceControlShutdownServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _ServiceControl_SelfUpdate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RepositoryState)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceControlServer).SelfUpdate(m, &serviceControlSelfUpdateServer{stream})
}

type ServiceControl_SelfUpdateServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

type serviceControlSelfUpdateServer struct {
	grpc.ServerStream
}

func (x *serviceControlSelfUpdateServer) Send(m *JobEvent) error {
	return x.ServerStream.SendMsg(m)
}

var _ServiceControl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stonesthrow.ServiceControl",
	HandlerType: (*ServiceControlServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Shutdown",
			Handler:       _ServiceControl_Shutdown_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SelfUpdate",
			Handler:       _ServiceControl_SelfUpdate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "stonesthrow/st.proto",
}

func init() { proto.RegisterFile("stonesthrow/st.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xcd, 0x72, 0x1b, 0x45,
	0x10, 0xce, 0xea, 0xcf, 0xbb, 0x2d, 0x47, 0x92, 0x87, 0xfc, 0x28, 0xaa, 0x90, 0xb8, 0x96, 0x14,
	0x18, 0x52, 0x25, 0x52, 0xca, 0x21, 0x10, 0x2a, 0x90, 0x48, 0x96, 0xed, 0x24, 0x26, 0x36, 0x23,
	0xfb, 0xc2, 0x01, 0xd5, 0x4a, 0x1a, 0x4b, 0x4b, 0x56, 0x33, 0xca, 0xcc, 0xac, 0x53, 0xe6, 0xcc,
	0x81, 0xe2, 0xcc, 0x21, 0x2f, 0xc2, 0x23, 0xe4, 0x15, 0x78, 0x0a, 0x1e, 0x80, 0x23, 0x35, 0x3f,
	0x2b, 0x79, 0x2d, 0x5b, 0x4e, 0x09, 0x6e, 0xd3, 0xad, 0xee, 0x6f, 0xfa, 0xe7, 0x9b, 0xee, 0x15,
	0x5c, 0x13, 0x92, 0x51, 0x22, 0xe4, 0x88, 0xb3, 0xb7, 0x5f, 0x0a, 0x59, 0x9f, 0x70, 0x26, 0x19,
	0x2a, 0x9e, 0xd2, 0xfa, 0x3f, 0xc2, 0x6a, 0x67, 0x44, 0xa2, 0xa8, 0xc5, 0xc6, 0xe3, 0x80, 0x0e,
	0x50, 0x15, 0x56, 0xfa, 0xe6, 0x58, 0x75, 0xd6, 0xb3, 0x1b, 0x1e, 0x4e, 0x44, 0x74, 0x1b, 0xbc,
	0x41, 0xc8, 0x49, 0x5f, 0x32, 0x7e, 0x52, 0xcd, 0xac, 0x3b, 0x1b, 0x1e, 0x9e, 0x29, 0x10, 0x82,
	0xdc, 0x88, 0x09, 0x59, 0xcd, 0xea, 0x1f, 0xf4, 0xd9, 0xff, 0xd3, 0x01, 0x4f, 0x83, 0x1f, 0x04,
	0xe2, 0x35, 0x7a, 0x78, 0x1a, 0xd9, 0xd9, 0x28, 0x36, 0x6e, 0xd5, 0x4f, 0x05, 0x52, 0x3f, 0x1d,
	0xc5, 0xec, 0xd2, 0xfb, 0x90, 0x17, 0x32, 0x90, 0x44, 0x5f, 0x58, 0x6c, 0x5c, 0x4f, 0xb9, 0xe0,
	0x98, 0x76, 0xd4, 0x8f, 0xd8, 0xd8, 0xa0, 0x7b, 0x50, 0x12, 0x27, 0x42, 0x92, 0x71, 0x57, 0x86,
	0x63, 0xd2, 0xa5, 0x42, 0x47, 0x93, 0xc5, 0xab, 0x46, 0x7b, 0x10, 0x8e, 0xc9, 0x2b, 0x81, 0xd6,
	0x61, 0x35, 0x16, 0x84, 0x4f, 0x6d, 0x72, 0xda, 0x06, 0x94, 0xce, 0x58, 0xf8, 0xdf, 0x43, 0x19,
	0x93, 0x09, 0x13, 0xa1, 0xca, 0x4c, 0xdf, 0x80, 0xee, 0x00, 0xf0, 0xa9, 0xca, 0x66, 0x7f, 0x4a,
	0x83, 0x6a, 0xe0, 0x72, 0x72, 0x1c, 0x8a, 0x90, 0x51, 0x5b, 0x82, 0xa9, 0xec, 0xff, 0x04, 0x6e,
	0x12, 0x29, 0xfa, 0x18, 0x40, 0xc8, 0x80, 0x4b, 0x7d, 0xbb, 0xae, 0x43, 0x16, 0x7b, 0x5a, 0xa3,
	0xee, 0x56, 0xd5, 0xe7, 0x31, 0xa5, 0x21, 0x1d, 0xea, 0x3b, 0x5c, 0x9c, 0x88, 0xe8, 0x16, 0xb8,
	0x84, 0x0e, 0x8c, 0x9b, 0xc9, 0x6a, 0x85, 0xd0, 0x81, 0x72, 0xf2, 0xff, 0x76, 0x00, 0x9a, 0x71,
	0x18, 0x0d, 0x08, 0x7f, 0xc1, 0x7a, 0xa8, 0x04, 0x99, 0xd0, 0x94, 0x38, 0x8f, 0x33, 0xa1, 0xee,
	0x28, 0x27, 0x6f, 0x62, 0x22, 0xa4, 0x8d, 0x3b, 0x11, 0xd1, 0x36, 0x54, 0x66, 0x29, 0x74, 0x4d,
	0x9d, 0xb3, 0xba, 0xce, 0xb7, 0xd3, 0x75, 0x4e, 0x17, 0x03, 0x97, 0xf9, 0x99, 0xea, 0x34, 0xc0,
	0xe3, 0x31, 0xb5, 0x08, 0xb9, 0x45, 0x9d, 0x72, 0x79, 0x52, 0x89, 0x47, 0x50, 0x14, 0xaa, 0xe5,
	0x5d, 0x19, 0x88, 0xd7, 0xa2, 0x9a, 0x5f, 0xcf, 0x6e, 0x14, 0x1b, 0x37, 0xe6, 0x29, 0xa1, 0xb8,
	0x83, 0x41, 0x24, 0x47, 0xe1, 0x3f, 0x86, 0xe2, 0x2c, 0x5b, 0x81, 0xee, 0x43, 0xee, 0x67, 0xd6,
	0x13, 0x9a, 0xad, 0xc5, 0xc6, 0xcd, 0x14, 0xc0, 0xcc, 0x0e, 0x6b, 0x23, 0xff, 0xd7, 0x2c, 0x5c,
	0xdd, 0x0e, 0x65, 0x93, 0x07, 0xb4, 0x3f, 0x7a, 0x4e, 0x8f, 0x18, 0x7a, 0x0a, 0x6e, 0x4f, 0x4b,
	0x24, 0x81, 0xb8, 0x97, 0x82, 0x48, 0x59, 0xcf, 0x24, 0x3c, 0xf5, 0x52, 0xad, 0x8f, 0x27, 0x42,
	0x72, 0x12, 0x8c, 0xab, 0x19, 0xfd, 0x64, 0xa6, 0x72, 0xed, 0x8f, 0x0c, 0x78, 0x53, 0x1f, 0xf5,
	0x46, 0x68, 0x60, 0xdb, 0xee, 0x61, 0x7d, 0x4e, 0x11, 0x27, 0x93, 0x26, 0x0e, 0xfa, 0x0c, 0xca,
	0xc9, 0x59, 0x74, 0x83, 0x11, 0x09, 0x06, 0xba, 0x3d, 0x79, 0x5c, 0x9a, 0xaa, 0x9f, 0x29, 0x2d,
	0xfa, 0x5c, 0x35, 0x32, 0x31, 0xec, 0x91, 0x51, 0x48, 0x07, 0xba, 0x0d, 0x79, 0x3c, 0x03, 0x68,
	0x6a, 0x35, 0xda, 0x81, 0x42, 0x9f, 0xd1, 0xa3, 0x70, 0x68, 0x2b, 0xfe, 0xe0, 0x43, 0xb2, 0xad,
	0xb7, 0xb4, 0x4b, 0x9b, 0x4a, 0x7e, 0x82, 0xad, 0x7f, 0xed, 0x6b, 0x28, 0x9e, 0x52, 0xa3, 0x0a,
	0x64, 0x5f, 0x93, 0x13, 0x9b, 0x9b, 0x3a, 0xa2, 0x6b, 0x90, 0x3f, 0x0e, 0xa2, 0x98, 0xd8, 0xbc,
	0x8c, 0xf0, 0x38, 0xf3, 0x95, 0xe3, 0xbf, 0x73, 0xc0, 0xdd, 0x65, 0xc3, 0xf6, 0x31, 0xa1, 0x72,
	0x3a, 0x39, 0x9c, 0xd9, 0xe4, 0x50, 0x60, 0x63, 0x31, 0xb4, 0x8e, 0xea, 0x88, 0x1e, 0x83, 0x2b,
	0xc8, 0x31, 0xe1, 0xa1, 0x3c, 0xd1, 0x45, 0x28, 0x35, 0xee, 0xa4, 0x22, 0x4f, 0xe0, 0xea, 0x1d,
	0x6b, 0x85, 0xa7, 0xf6, 0xfe, 0x17, 0xe0, 0x26, 0x5a, 0xe4, 0x41, 0xbe, 0x8d, 0xf1, 0x1e, 0xae,
	0x5c, 0x41, 0x2e, 0xe4, 0x9e, 0xbf, 0xda, 0xda, 0xab, 0x38, 0x4a, 0xb9, 0xd9, 0x6e, 0x1e, 0x6e,
	0x57, 0x32, 0xfe, 0x0e, 0xac, 0x35, 0xc9, 0x30, 0xa4, 0x76, 0x12, 0x99, 0x10, 0x97, 0x19, 0x5d,
	0xfe, 0x6f, 0x0e, 0x20, 0xab, 0xdc, 0x8b, 0xe5, 0x24, 0x96, 0x06, 0xeb, 0x5b, 0x28, 0x58, 0xb2,
	0x38, 0x3a, 0x8d, 0x4f, 0x53, 0x50, 0xf3, 0x0e, 0xf5, 0x8e, 0xb6, 0xc6, 0xd6, 0x0b, 0xdd, 0x80,
	0x02, 0xd3, 0xbf, 0xda, 0xea, 0x58, 0xc9, 0xaf, 0x41, 0xc1, 0x58, 0xa2, 0x15, 0xc8, 0xee, 0x1d,
	0x1e, 0x54, 0xae, 0xa8, 0x43, 0x1b, 0xe3, 0x8a, 0xe3, 0xff, 0x02, 0xe5, 0x36, 0x1d, 0xa4, 0x52,
	0xba, 0x0b, 0x45, 0x4e, 0x64, 0xcc, 0x69, 0xb7, 0xcf, 0x06, 0xc4, 0x8e, 0x0b, 0x30, 0xaa, 0x16,
	0x1b, 0x9c, 0x37, 0x4c, 0x33, 0x1f, 0x30, 0x4c, 0xb3, 0x73, 0xc3, 0xf4, 0xbd, 0x03, 0x68, 0x4a,
	0x24, 0xf5, 0x82, 0xcd, 0xfd, 0x37, 0xa0, 0x60, 0x5e, 0x90, 0xed, 0xbb, 0x95, 0x54, 0x79, 0x38,
	0x11, 0x71, 0x64, 0xd2, 0x3b, 0x5b, 0x9e, 0x79, 0xa0, 0x3a, 0xd6, 0xd6, 0xd8, 0x7a, 0x2d, 0x1a,
	0xc4, 0xea, 0x4e, 0x4e, 0x02, 0xc1, 0xa8, 0x7e, 0x1c, 0x1e, 0xb6, 0x92, 0xff, 0x09, 0x14, 0x0c,
	0x0a, 0xba, 0x0a, 0x5e, 0xe7, 0xb0, 0xd5, 0x6a, 0xb7, 0x37, 0xdb, 0x9b, 0x95, 0x2b, 0x08, 0xa0,
	0xb0, 0xf5, 0xec, 0xf9, 0x6e, 0x7b, 0xb3, 0xe2, 0xf8, 0xff, 0x64, 0xc0, 0x7d, 0xc1, 0x7a, 0x26,
	0xfa, 0x06, 0x78, 0x11, 0x1b, 0x76, 0x89, 0x12, 0x2c, 0x25, 0xae, 0x9f, 0x4b, 0x47, 0xec, 0x46,
	0x09, 0xcf, 0x5f, 0xc1, 0x47, 0x3d, 0xc5, 0xac, 0xae, 0x25, 0x88, 0xf5, 0x36, 0x8b, 0x2d, 0x4d,
	0xe6, 0x39, 0x06, 0xe2, 0xb5, 0xde, 0x1c, 0x29, 0x7f, 0x80, 0x6b, 0x09, 0x92, 0xa1, 0x80, 0x05,
	0x34, 0x13, 0xfc, 0xee, 0x25, 0xb4, 0xc2, 0xa8, 0x3f, 0xcf, 0xcd, 0x1d, 0x58, 0x53, 0x4b, 0x26,
	0x1d, 0x60, 0xee, 0x9c, 0x8d, 0x70, 0x86, 0x4d, 0xb8, 0x4c, 0xce, 0xd0, 0xeb, 0x25, 0xac, 0x99,
	0x86, 0xea, 0xf1, 0x6e, 0x91, 0xf2, 0xe7, 0x44, 0x36, 0xdf, 0x51, 0x5c, 0xee, 0xa5, 0x15, 0xfe,
	0x1b, 0x58, 0xd5, 0x93, 0x7c, 0x6f, 0x22, 0xd5, 0x24, 0x53, 0x1b, 0x4d, 0x06, 0x7c, 0x48, 0xa4,
	0x48, 0xbe, 0x51, 0xac, 0x78, 0xee, 0x46, 0xcb, 0x2c, 0xb1, 0xd1, 0xfc, 0xdf, 0x1d, 0x00, 0x1c,
	0xd3, 0xe4, 0xc6, 0xa5, 0xbe, 0x5d, 0xfe, 0xb7, 0x60, 0xee, 0x01, 0x1c, 0xe8, 0x04, 0x77, 0x43,
	0xa1, 0x5f, 0x8e, 0x49, 0xd7, 0x26, 0x6f, 0xa5, 0xc6, 0x5f, 0x59, 0x58, 0xdb, 0x8f, 0x02, 0x79,
	0xc4, 0xf8, 0x58, 0x97, 0x6b, 0x47, 0x4d, 0xd2, 0x26, 0xb8, 0xca, 0x4b, 0xaf, 0xca, 0x85, 0xd7,
	0xd6, 0xaa, 0x17, 0xac, 0x4e, 0x81, 0x9e, 0x80, 0xfb, 0x32, 0x8c, 0x22, 0x7d, 0xbe, 0xd0, 0xaa,
	0x96, 0x7e, 0x00, 0xc9, 0x53, 0x79, 0xe0, 0xa0, 0x6f, 0x20, 0xaf, 0xed, 0xd0, 0xad, 0x79, 0x5f,
	0x5b, 0xe0, 0x8b, 0x9d, 0x1f, 0x41, 0x16, 0xc7, 0x14, 0xdd, 0x3c, 0xfb, 0x39, 0x71, 0xa9, 0xe3,
	0x53, 0x58, 0x69, 0x45, 0xac, 0xd7, 0x23, 0xfc, 0x92, 0xbc, 0x17, 0x21, 0xec, 0x73, 0x32, 0x09,
	0x38, 0x59, 0x16, 0x61, 0x13, 0x8a, 0xaa, 0xf8, 0x07, 0x96, 0x9d, 0x8b, 0x51, 0xd2, 0x29, 0xce,
	0x1a, 0xde, 0x78, 0x9f, 0x83, 0xd2, 0xcc, 0x58, 0x77, 0xf5, 0x25, 0x94, 0xb7, 0x89, 0x7d, 0x38,
	0x66, 0x09, 0x5f, 0x02, 0x5e, 0xbb, 0x78, 0xcd, 0xa3, 0x2d, 0x28, 0x77, 0xce, 0x80, 0x2d, 0x30,
	0xbf, 0x38, 0xdb, 0x6d, 0xa8, 0xec, 0xc7, 0x51, 0xb4, 0xc5, 0xd9, 0xf8, 0xd0, 0x7e, 0x00, 0x2d,
	0x07, 0xd4, 0x86, 0xd2, 0x7e, 0x2c, 0x46, 0x07, 0xec, 0xbf, 0xc1, 0x7c, 0xa7, 0x36, 0x62, 0x20,
	0x63, 0xb1, 0x6c, 0xfb, 0x9a, 0xe0, 0x75, 0x4e, 0x68, 0x7f, 0x97, 0xf5, 0x83, 0x68, 0x59, 0x8c,
	0x27, 0x90, 0x53, 0x18, 0xcb, 0xba, 0xbf, 0x80, 0x35, 0xcb, 0xc1, 0x2d, 0xc6, 0x31, 0xe9, 0x93,
	0xf0, 0x78, 0x59, 0x36, 0x36, 0xde, 0x39, 0x50, 0xea, 0x10, 0x7e, 0x1c, 0xf6, 0x49, 0x8b, 0x51,
	0xc9, 0x59, 0x84, 0x9e, 0x81, 0xdb, 0x19, 0xc5, 0x72, 0xc0, 0xde, 0xd2, 0x65, 0x23, 0x6c, 0x01,
	0x74, 0x48, 0x74, 0x74, 0x38, 0x19, 0xa8, 0xaf, 0xfa, 0xe5, 0x40, 0x7a, 0x05, 0xfd, 0xcf, 0xf4,
	0xe1, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x95, 0xae, 0xad, 0x86, 0xb1, 0x0e, 0x00, 0x00,
}
